-- Sprint 9 — Exams, results and report cards.
--
-- Six tables, and the module hangs off three gates that are deliberately
-- separate:
--
--   exams.is_published           the datesheet. What makes admit cards issuable.
--   exam_subjects.results_status one paper: draft -> submitted -> published.
--   exam_terms.is_published      the report card for the whole term.
--
-- Collapsing any two of them would mean a school could not tell students when
-- an exam is without also showing marks that do not exist yet, or could not
-- correct one subject in week three without having already put a half-finished
-- report card in front of a parent.
--
-- Re-sits are attempt 2 of the same paper, not a second exam: a second exam
-- would double every tabulation sheet and make "position in class" ambiguous.
-- exam_subjects.resit_status carries its own lifecycle, so a re-sit sat in week
-- six does not drag the whole paper back into draft, and its marks are not
-- visible the instant they are typed merely because the original was published.
--
-- Marks are NUMERIC for the same reason money is: a percentage computed through
-- a float is a report card that changes after it was handed out. Absence is a
-- column and marks_obtained is nullable -- a child who did not sit the paper has
-- no mark, and storing zero would drag their aggregate down as though they had
-- sat it and answered nothing. See db/schema/exam-results.ts.
--
-- Unlike 0011-0015 this one was generated by drizzle-kit against the schema
-- files, so the snapshot in meta/ and this file cannot disagree. Only this
-- header is hand-written.

CREATE TABLE "grading_bands" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"scheme_id" uuid NOT NULL,
	"label" text NOT NULL,
	"min_percentage" numeric(5, 2) NOT NULL,
	"max_percentage" numeric(5, 2) NOT NULL,
	"gpa" numeric(4, 2),
	"remark" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "grading_bands_range_check" CHECK ("grading_bands"."min_percentage" >= 0 AND "grading_bands"."max_percentage" <= 100 AND "grading_bands"."min_percentage" <= "grading_bands"."max_percentage")
);
--> statement-breakpoint
CREATE TABLE "grading_schemes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"name" text NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "exam_terms" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"academic_year_id" uuid NOT NULL,
	"name" text NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"grading_scheme_id" uuid,
	"is_published" boolean DEFAULT false NOT NULL,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "exams" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"term_id" uuid NOT NULL,
	"grade_id" uuid NOT NULL,
	"section_id" uuid NOT NULL,
	"title" text NOT NULL,
	"exam_date" date NOT NULL,
	"instructions" text,
	"is_published" boolean DEFAULT false NOT NULL,
	"published_at" timestamp with time zone,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "exam_subjects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"exam_id" uuid NOT NULL,
	"subject_id" uuid NOT NULL,
	"max_marks" numeric(6, 2) NOT NULL,
	"passing_marks" numeric(6, 2) NOT NULL,
	"exam_date" date,
	"slot" text,
	"order_index" integer DEFAULT 0 NOT NULL,
	"results_status" text DEFAULT 'draft' NOT NULL,
	"resit_status" text DEFAULT 'none' NOT NULL,
	"published_by" uuid,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "exam_subjects_results_status_check" CHECK ("exam_subjects"."results_status" IN ('draft', 'submitted', 'published')),
	CONSTRAINT "exam_subjects_resit_status_check" CHECK ("exam_subjects"."resit_status" IN ('none', 'draft', 'submitted', 'published')),
	CONSTRAINT "exam_subjects_marks_check" CHECK ("exam_subjects"."max_marks" > 0 AND "exam_subjects"."passing_marks" >= 0 AND "exam_subjects"."passing_marks" <= "exam_subjects"."max_marks")
);
--> statement-breakpoint
CREATE TABLE "exam_results" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"exam_subject_id" uuid NOT NULL,
	"student_profile_id" uuid NOT NULL,
	"attempt" integer DEFAULT 1 NOT NULL,
	"marks_obtained" numeric(6, 2),
	"is_absent" boolean DEFAULT false NOT NULL,
	"remarks" text,
	"entered_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "exam_results_attempt_check" CHECK ("exam_results"."attempt" IN (1, 2)),
	CONSTRAINT "exam_results_marks_check" CHECK (("exam_results"."is_absent" AND "exam_results"."marks_obtained" IS NULL) OR (NOT "exam_results"."is_absent" AND "exam_results"."marks_obtained" >= 0))
);
--> statement-breakpoint
ALTER TABLE "grading_bands" ADD CONSTRAINT "grading_bands_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grading_bands" ADD CONSTRAINT "grading_bands_scheme_id_grading_schemes_id_fk" FOREIGN KEY ("scheme_id") REFERENCES "public"."grading_schemes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grading_schemes" ADD CONSTRAINT "grading_schemes_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_terms" ADD CONSTRAINT "exam_terms_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_terms" ADD CONSTRAINT "exam_terms_academic_year_id_academic_years_id_fk" FOREIGN KEY ("academic_year_id") REFERENCES "public"."academic_years"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_terms" ADD CONSTRAINT "exam_terms_grading_scheme_id_grading_schemes_id_fk" FOREIGN KEY ("grading_scheme_id") REFERENCES "public"."grading_schemes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exams" ADD CONSTRAINT "exams_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exams" ADD CONSTRAINT "exams_term_id_exam_terms_id_fk" FOREIGN KEY ("term_id") REFERENCES "public"."exam_terms"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exams" ADD CONSTRAINT "exams_grade_id_grades_id_fk" FOREIGN KEY ("grade_id") REFERENCES "public"."grades"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exams" ADD CONSTRAINT "exams_section_id_sections_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."sections"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exams" ADD CONSTRAINT "exams_created_by_school_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."school_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_subjects" ADD CONSTRAINT "exam_subjects_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_subjects" ADD CONSTRAINT "exam_subjects_exam_id_exams_id_fk" FOREIGN KEY ("exam_id") REFERENCES "public"."exams"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_subjects" ADD CONSTRAINT "exam_subjects_subject_id_subjects_id_fk" FOREIGN KEY ("subject_id") REFERENCES "public"."subjects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_subjects" ADD CONSTRAINT "exam_subjects_published_by_school_users_id_fk" FOREIGN KEY ("published_by") REFERENCES "public"."school_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_results" ADD CONSTRAINT "exam_results_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_results" ADD CONSTRAINT "exam_results_exam_subject_id_exam_subjects_id_fk" FOREIGN KEY ("exam_subject_id") REFERENCES "public"."exam_subjects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_results" ADD CONSTRAINT "exam_results_student_profile_id_student_profiles_id_fk" FOREIGN KEY ("student_profile_id") REFERENCES "public"."student_profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_results" ADD CONSTRAINT "exam_results_entered_by_school_users_id_fk" FOREIGN KEY ("entered_by") REFERENCES "public"."school_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "grading_bands_location_id_idx" ON "grading_bands" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "grading_bands_scheme_id_idx" ON "grading_bands" USING btree ("scheme_id");--> statement-breakpoint
CREATE UNIQUE INDEX "grading_bands_scheme_id_label_idx" ON "grading_bands" USING btree ("scheme_id","label");--> statement-breakpoint
CREATE INDEX "grading_schemes_location_id_idx" ON "grading_schemes" USING btree ("location_id");--> statement-breakpoint
CREATE UNIQUE INDEX "grading_schemes_location_id_name_idx" ON "grading_schemes" USING btree ("location_id","name");--> statement-breakpoint
CREATE INDEX "exam_terms_location_id_idx" ON "exam_terms" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "exam_terms_location_id_academic_year_idx" ON "exam_terms" USING btree ("location_id","academic_year_id");--> statement-breakpoint
CREATE UNIQUE INDEX "exam_terms_location_year_name_idx" ON "exam_terms" USING btree ("location_id","academic_year_id","name");--> statement-breakpoint
CREATE INDEX "exams_location_id_idx" ON "exams" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "exams_location_id_term_idx" ON "exams" USING btree ("location_id","term_id");--> statement-breakpoint
CREATE INDEX "exams_location_id_section_idx" ON "exams" USING btree ("location_id","section_id");--> statement-breakpoint
CREATE INDEX "exams_location_id_grade_idx" ON "exams" USING btree ("location_id","grade_id");--> statement-breakpoint
CREATE INDEX "exam_subjects_location_id_idx" ON "exam_subjects" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "exam_subjects_exam_id_idx" ON "exam_subjects" USING btree ("exam_id");--> statement-breakpoint
CREATE UNIQUE INDEX "exam_subjects_exam_id_subject_id_idx" ON "exam_subjects" USING btree ("exam_id","subject_id");--> statement-breakpoint
CREATE INDEX "exam_results_location_id_idx" ON "exam_results" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "exam_results_exam_subject_id_idx" ON "exam_results" USING btree ("exam_subject_id");--> statement-breakpoint
CREATE INDEX "exam_results_location_id_student_idx" ON "exam_results" USING btree ("location_id","student_profile_id");--> statement-breakpoint
CREATE UNIQUE INDEX "exam_results_paper_student_attempt_idx" ON "exam_results" USING btree ("location_id","exam_subject_id","student_profile_id","attempt");