-- Sprint 10 — school onboarding: import, promotion, transfer, family fees.
--
-- `SPRINTS.md` names this migration `0017_sprint10_onboarding.sql`. That number
-- was taken by `0017_branding_presets.sql` on 2026-08-09, so this is `0018`.
--
-- Generated by drizzle-kit from the schema files, per STATE.md §5n: only the
-- hand-written migrations have had snapshots that could disagree with them.
--
-- Note the `role_permissions` CHECK at the end. It regenerated on its own,
-- because `db/schema/role-permissions.ts` builds the constraint from the
-- `PERMISSIONS` array rather than restating the keys. That is what makes
-- STATE.md §5o's failure — five permission keys shipped that the database
-- refused — structurally impossible here rather than merely remembered.
--
-- The three new keys are `students.import`, `students.promote` and
-- `students.transfer`.

CREATE TABLE "student_import_batches" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"file_name" text NOT NULL,
	"status" text DEFAULT 'uploaded' NOT NULL,
	"source_columns" jsonb NOT NULL,
	"column_map" jsonb,
	"academic_year_id" uuid,
	"section_id" uuid,
	"total_rows" integer DEFAULT 0 NOT NULL,
	"valid_rows" integer DEFAULT 0 NOT NULL,
	"invalid_rows" integer DEFAULT 0 NOT NULL,
	"created_rows" integer DEFAULT 0 NOT NULL,
	"skipped_rows" integer DEFAULT 0 NOT NULL,
	"failed_rows" integer DEFAULT 0 NOT NULL,
	"uploaded_by_uid" text,
	"validated_at" timestamp with time zone,
	"committed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "student_import_batches_status_check" CHECK ("student_import_batches"."status" IN ('uploaded', 'validated', 'committed', 'cancelled'))
);
--> statement-breakpoint
CREATE TABLE "student_import_rows" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"batch_id" uuid NOT NULL,
	"row_number" integer NOT NULL,
	"raw" jsonb NOT NULL,
	"outcome" text DEFAULT 'pending' NOT NULL,
	"errors" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"student_profile_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "student_import_rows_outcome_check" CHECK ("student_import_rows"."outcome" IN ('pending', 'invalid', 'created', 'skipped', 'failed'))
);
--> statement-breakpoint
CREATE TABLE "promotion_decisions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"run_id" uuid NOT NULL,
	"student_profile_id" uuid NOT NULL,
	"from_enrollment_id" uuid NOT NULL,
	"decision" text DEFAULT 'promote' NOT NULL,
	"to_section_id" uuid,
	"created_enrollment_id" uuid,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "promotion_decisions_decision_check" CHECK ("promotion_decisions"."decision" IN ('promote', 'retain', 'graduate'))
);
--> statement-breakpoint
CREATE TABLE "promotion_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"grade_id" uuid NOT NULL,
	"from_academic_year_id" uuid NOT NULL,
	"to_academic_year_id" uuid NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"promoted_count" integer DEFAULT 0 NOT NULL,
	"retained_count" integer DEFAULT 0 NOT NULL,
	"graduated_count" integer DEFAULT 0 NOT NULL,
	"applied_by_uid" text,
	"applied_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "promotion_runs_status_check" CHECK ("promotion_runs"."status" IN ('draft', 'applied'))
);
--> statement-breakpoint
CREATE TABLE "student_transfers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"student_profile_id" uuid NOT NULL,
	"academic_year_id" uuid NOT NULL,
	"from_branch_id" uuid NOT NULL,
	"to_branch_id" uuid NOT NULL,
	"from_section_id" uuid NOT NULL,
	"to_section_id" uuid NOT NULL,
	"from_enrollment_id" uuid NOT NULL,
	"to_enrollment_id" uuid,
	"effective_date" date NOT NULL,
	"prorated_credit" numeric(12, 2) DEFAULT '0' NOT NULL,
	"prorated_charge" numeric(12, 2) DEFAULT '0' NOT NULL,
	"reason" text,
	"transferred_by_uid" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "student_transfers_branch_differs_check" CHECK ("student_transfers"."from_branch_id" <> "student_transfers"."to_branch_id")
);
--> statement-breakpoint
CREATE TABLE "family_challans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"guardian_id" uuid NOT NULL,
	"academic_year_id" uuid NOT NULL,
	"challan_number" text NOT NULL,
	"billing_month" integer,
	"billing_year" integer,
	"due_date" date NOT NULL,
	"issue_date" date DEFAULT now() NOT NULL,
	"total_amount" numeric(12, 2) NOT NULL,
	"paid_amount" numeric(12, 2) DEFAULT '0' NOT NULL,
	"status" text DEFAULT 'unpaid' NOT NULL,
	"notes" text,
	"generated_by_uid" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "family_challans_challan_number_unique" UNIQUE("challan_number"),
	CONSTRAINT "family_challans_status_check" CHECK ("family_challans"."status" IN ('unpaid', 'partial', 'paid', 'cancelled'))
);
--> statement-breakpoint
ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_check";--> statement-breakpoint
ALTER TABLE "fee_challans" ADD COLUMN "family_challan_id" uuid;--> statement-breakpoint
ALTER TABLE "student_import_batches" ADD CONSTRAINT "student_import_batches_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_import_batches" ADD CONSTRAINT "student_import_batches_academic_year_id_academic_years_id_fk" FOREIGN KEY ("academic_year_id") REFERENCES "public"."academic_years"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_import_batches" ADD CONSTRAINT "student_import_batches_section_id_sections_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."sections"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_import_rows" ADD CONSTRAINT "student_import_rows_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_import_rows" ADD CONSTRAINT "student_import_rows_batch_id_student_import_batches_id_fk" FOREIGN KEY ("batch_id") REFERENCES "public"."student_import_batches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_import_rows" ADD CONSTRAINT "student_import_rows_student_profile_id_student_profiles_id_fk" FOREIGN KEY ("student_profile_id") REFERENCES "public"."student_profiles"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_decisions" ADD CONSTRAINT "promotion_decisions_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_decisions" ADD CONSTRAINT "promotion_decisions_run_id_promotion_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."promotion_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_decisions" ADD CONSTRAINT "promotion_decisions_student_profile_id_student_profiles_id_fk" FOREIGN KEY ("student_profile_id") REFERENCES "public"."student_profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_decisions" ADD CONSTRAINT "promotion_decisions_from_enrollment_id_student_enrollments_id_fk" FOREIGN KEY ("from_enrollment_id") REFERENCES "public"."student_enrollments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_decisions" ADD CONSTRAINT "promotion_decisions_to_section_id_sections_id_fk" FOREIGN KEY ("to_section_id") REFERENCES "public"."sections"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_decisions" ADD CONSTRAINT "promotion_decisions_created_enrollment_id_student_enrollments_id_fk" FOREIGN KEY ("created_enrollment_id") REFERENCES "public"."student_enrollments"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_runs" ADD CONSTRAINT "promotion_runs_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_runs" ADD CONSTRAINT "promotion_runs_grade_id_grades_id_fk" FOREIGN KEY ("grade_id") REFERENCES "public"."grades"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_runs" ADD CONSTRAINT "promotion_runs_from_academic_year_id_academic_years_id_fk" FOREIGN KEY ("from_academic_year_id") REFERENCES "public"."academic_years"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_runs" ADD CONSTRAINT "promotion_runs_to_academic_year_id_academic_years_id_fk" FOREIGN KEY ("to_academic_year_id") REFERENCES "public"."academic_years"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_transfers" ADD CONSTRAINT "student_transfers_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_transfers" ADD CONSTRAINT "student_transfers_student_profile_id_student_profiles_id_fk" FOREIGN KEY ("student_profile_id") REFERENCES "public"."student_profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_transfers" ADD CONSTRAINT "student_transfers_academic_year_id_academic_years_id_fk" FOREIGN KEY ("academic_year_id") REFERENCES "public"."academic_years"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_transfers" ADD CONSTRAINT "student_transfers_from_branch_id_branches_id_fk" FOREIGN KEY ("from_branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_transfers" ADD CONSTRAINT "student_transfers_to_branch_id_branches_id_fk" FOREIGN KEY ("to_branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_transfers" ADD CONSTRAINT "student_transfers_from_section_id_sections_id_fk" FOREIGN KEY ("from_section_id") REFERENCES "public"."sections"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_transfers" ADD CONSTRAINT "student_transfers_to_section_id_sections_id_fk" FOREIGN KEY ("to_section_id") REFERENCES "public"."sections"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_transfers" ADD CONSTRAINT "student_transfers_from_enrollment_id_student_enrollments_id_fk" FOREIGN KEY ("from_enrollment_id") REFERENCES "public"."student_enrollments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_transfers" ADD CONSTRAINT "student_transfers_to_enrollment_id_student_enrollments_id_fk" FOREIGN KEY ("to_enrollment_id") REFERENCES "public"."student_enrollments"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "family_challans" ADD CONSTRAINT "family_challans_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "family_challans" ADD CONSTRAINT "family_challans_guardian_id_student_guardians_id_fk" FOREIGN KEY ("guardian_id") REFERENCES "public"."student_guardians"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "family_challans" ADD CONSTRAINT "family_challans_academic_year_id_academic_years_id_fk" FOREIGN KEY ("academic_year_id") REFERENCES "public"."academic_years"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "student_import_batches_location_id_idx" ON "student_import_batches" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "student_import_batches_location_status_idx" ON "student_import_batches" USING btree ("location_id","status");--> statement-breakpoint
CREATE INDEX "student_import_rows_location_id_idx" ON "student_import_rows" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "student_import_rows_batch_id_idx" ON "student_import_rows" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX "student_import_rows_batch_outcome_idx" ON "student_import_rows" USING btree ("batch_id","outcome");--> statement-breakpoint
CREATE UNIQUE INDEX "student_import_rows_batch_row_idx" ON "student_import_rows" USING btree ("batch_id","row_number");--> statement-breakpoint
CREATE INDEX "promotion_decisions_location_id_idx" ON "promotion_decisions" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "promotion_decisions_run_id_idx" ON "promotion_decisions" USING btree ("run_id");--> statement-breakpoint
CREATE UNIQUE INDEX "promotion_decisions_run_student_idx" ON "promotion_decisions" USING btree ("run_id","student_profile_id");--> statement-breakpoint
CREATE INDEX "promotion_runs_location_id_idx" ON "promotion_runs" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "promotion_runs_location_status_idx" ON "promotion_runs" USING btree ("location_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "promotion_runs_grade_years_idx" ON "promotion_runs" USING btree ("grade_id","from_academic_year_id","to_academic_year_id");--> statement-breakpoint
CREATE INDEX "student_transfers_location_id_idx" ON "student_transfers" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "student_transfers_student_profile_id_idx" ON "student_transfers" USING btree ("student_profile_id");--> statement-breakpoint
CREATE INDEX "student_transfers_location_effective_idx" ON "student_transfers" USING btree ("location_id","effective_date");--> statement-breakpoint
CREATE INDEX "family_challans_location_id_idx" ON "family_challans" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "family_challans_guardian_id_idx" ON "family_challans" USING btree ("guardian_id");--> statement-breakpoint
CREATE INDEX "family_challans_location_status_idx" ON "family_challans" USING btree ("location_id","status");--> statement-breakpoint
CREATE INDEX "family_challans_location_due_date_idx" ON "family_challans" USING btree ("location_id","due_date");--> statement-breakpoint
ALTER TABLE "fee_challans" ADD CONSTRAINT "fee_challans_family_challan_id_family_challans_id_fk" FOREIGN KEY ("family_challan_id") REFERENCES "public"."family_challans"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "fee_challans_family_challan_id_idx" ON "fee_challans" USING btree ("family_challan_id");--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_check" CHECK (permission IN ('users.read', 'users.write', 'admissions.read', 'admissions.write', 'students.import', 'students.promote', 'students.transfer', 'fees.read', 'fees.write', 'academics.read', 'academics.write', 'attendance.mark', 'exams.read', 'exams.write', 'exams.publish', 'results.enter', 'results.publish', 'hr.read', 'hr.write', 'payroll.read', 'payroll.write', 'settings.read', 'settings.write', 'permissions.manage'));