-- Sprint 11 — Communications: announcements, notice board, delivery log.
--
-- Three tables for one message: what was said, who it was delivered to, and who
-- has read it.
--
-- The original plan built this entirely on GoHighLevel Conversations. GHL is
-- opt-in per school now, so the default delivery path is ours: the notice board
-- on the four portals always happens, email over the Sprint 0 outbox happens
-- when the sender asks for it, and WhatsApp is reached only where the paid
-- add-on module is on. A school that has connected nothing still gets working
-- announcements.
--
-- The audience is one tagged jsonb object rather than three nullable id
-- columns. Three columns would make every combination representable, including
-- the ones that mean nothing -- a row carrying both a grade and a role has no
-- agreed reading, and every query would have to invent one.
--
-- announcement_recipients is written once, at send, and holds the *resolved*
-- audience. Recomputing it later would answer "who got this" differently as
-- soon as a child changed section, and that is exactly the question asked after
-- something goes wrong. outbox_id is ON DELETE SET NULL for the same reason:
-- the queue gets drained and pruned, and the record of the send outlives the
-- message.
--
-- Generated by drizzle-kit against the schema files, so the snapshot in meta/
-- and this file cannot disagree. Only this header is hand-written.

CREATE TABLE "announcement_reads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"announcement_id" uuid NOT NULL,
	"school_user_id" uuid NOT NULL,
	"read_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "announcement_recipients" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"announcement_id" uuid NOT NULL,
	"school_user_id" uuid NOT NULL,
	"channel" text NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"detail" text,
	"outbox_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "announcement_recipients_channel_check" CHECK ("announcement_recipients"."channel" IN ('notice', 'email', 'whatsapp')),
	CONSTRAINT "announcement_recipients_status_check" CHECK ("announcement_recipients"."status" IN ('queued', 'sent', 'failed', 'unreachable'))
);
--> statement-breakpoint
CREATE TABLE "announcements" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"branch_id" uuid,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"audience" jsonb NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"send_email" boolean DEFAULT false NOT NULL,
	"scheduled_at" timestamp with time zone,
	"sent_at" timestamp with time zone,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "announcements_status_check" CHECK ("announcements"."status" IN ('draft', 'scheduled', 'sent')),
	CONSTRAINT "announcements_sent_at_check" CHECK (("announcements"."status" = 'sent') = ("announcements"."sent_at" IS NOT NULL)),
	CONSTRAINT "announcements_scheduled_at_check" CHECK ("announcements"."status" <> 'scheduled' OR "announcements"."scheduled_at" IS NOT NULL)
);
--> statement-breakpoint
ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_check";--> statement-breakpoint
ALTER TABLE "announcement_reads" ADD CONSTRAINT "announcement_reads_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_reads" ADD CONSTRAINT "announcement_reads_announcement_id_announcements_id_fk" FOREIGN KEY ("announcement_id") REFERENCES "public"."announcements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_reads" ADD CONSTRAINT "announcement_reads_school_user_id_school_users_id_fk" FOREIGN KEY ("school_user_id") REFERENCES "public"."school_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_recipients" ADD CONSTRAINT "announcement_recipients_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_recipients" ADD CONSTRAINT "announcement_recipients_announcement_id_announcements_id_fk" FOREIGN KEY ("announcement_id") REFERENCES "public"."announcements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_recipients" ADD CONSTRAINT "announcement_recipients_school_user_id_school_users_id_fk" FOREIGN KEY ("school_user_id") REFERENCES "public"."school_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_recipients" ADD CONSTRAINT "announcement_recipients_outbox_id_email_outbox_id_fk" FOREIGN KEY ("outbox_id") REFERENCES "public"."email_outbox"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcements" ADD CONSTRAINT "announcements_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcements" ADD CONSTRAINT "announcements_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcements" ADD CONSTRAINT "announcements_created_by_school_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."school_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "announcement_reads_location_user_idx" ON "announcement_reads" USING btree ("location_id","school_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "announcement_reads_unique_idx" ON "announcement_reads" USING btree ("announcement_id","school_user_id");--> statement-breakpoint
CREATE INDEX "announcement_recipients_location_id_idx" ON "announcement_recipients" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "announcement_recipients_announcement_id_idx" ON "announcement_recipients" USING btree ("announcement_id");--> statement-breakpoint
CREATE INDEX "announcement_recipients_location_user_idx" ON "announcement_recipients" USING btree ("location_id","school_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "announcement_recipients_unique_idx" ON "announcement_recipients" USING btree ("announcement_id","school_user_id","channel");--> statement-breakpoint
CREATE INDEX "announcements_location_id_idx" ON "announcements" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "announcements_location_id_status_sent_idx" ON "announcements" USING btree ("location_id","status","sent_at");--> statement-breakpoint
CREATE INDEX "announcements_location_id_branch_idx" ON "announcements" USING btree ("location_id","branch_id");--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_check" CHECK (permission IN ('users.read', 'users.write', 'admissions.read', 'admissions.write', 'students.import', 'students.promote', 'students.transfer', 'fees.read', 'fees.write', 'academics.read', 'academics.write', 'attendance.mark', 'exams.read', 'exams.write', 'exams.publish', 'results.enter', 'results.publish', 'hr.read', 'hr.write', 'payroll.read', 'payroll.write', 'comms.read', 'comms.write', 'comms.send', 'settings.read', 'settings.write', 'permissions.manage'));