-- Sprint 13 — portal completion, the PWA shell, and BR4 multiple principals.
--
-- Three tables and one column. Nothing here changes how a single existing row
-- behaves, and that is deliberate in each case:
--
--   schools.principal_model defaults to 'single', which is what every school
--   already is. The assignment screen does not appear and the resolver returns
--   an unnarrowed scope, so a school with one head is never made to configure
--   one.
--
--   notification_preferences has no back-fill. An absent row means every email
--   category is on -- the same rule role_permissions follows, and for the same
--   reason: a preferences table that had to be back-filled would silently mute
--   whoever it missed.
--
--   principal_assignments narrows what a head sees. It does NOT introduce a
--   role. The source document proposed a dynamic `principal_${division}` role;
--   that is refused, because school_users.role is a CHECK-constrained text
--   column and a role invented per division puts unbounded user input inside
--   it. The role stays `principal`; the assignment scopes it.
--
-- The one permission key added, principals.manage, is why the role_permissions
-- CHECK constraint is dropped and recreated. Same procedure as 0022. It goes to
-- school_admin only: a head who could edit assignments could widen their own
-- scope, which would make BR4 a suggestion rather than a boundary.
--
-- lesson_plans.week_starting is CHECKed to be a Monday. A plan filed against a
-- Thursday would sit between two weeks in every list that shows it.
--
-- Generated by drizzle-kit against the schema files, so the snapshot in meta/
-- and this file cannot disagree. Only this header is hand-written.

CREATE TABLE "principal_assignments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"school_user_id" uuid NOT NULL,
	"branch_id" uuid,
	"division_name" text,
	"grade_ids" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"starts_on" date NOT NULL,
	"ends_on" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "principal_assignments_dates_check" CHECK ("principal_assignments"."ends_on" IS NULL OR "principal_assignments"."ends_on" >= "principal_assignments"."starts_on"),
	CONSTRAINT "principal_assignments_division_check" CHECK ("principal_assignments"."division_name" IS NULL OR length("principal_assignments"."division_name") BETWEEN 1 AND 60)
);
--> statement-breakpoint
CREATE TABLE "lesson_plans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"teacher_id" uuid NOT NULL,
	"section_id" uuid NOT NULL,
	"subject_id" uuid NOT NULL,
	"week_starting" date NOT NULL,
	"title" text NOT NULL,
	"body" text DEFAULT '' NOT NULL,
	"homework" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lesson_plans_status_check" CHECK ("lesson_plans"."status" IN ('draft', 'shared')),
	CONSTRAINT "lesson_plans_week_starting_check" CHECK (extract(isodow from "lesson_plans"."week_starting") = 1),
	CONSTRAINT "lesson_plans_title_check" CHECK (length("lesson_plans"."title") BETWEEN 1 AND 160)
);
--> statement-breakpoint
CREATE TABLE "notification_preferences" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"school_user_id" uuid NOT NULL,
	"email_announcements" boolean DEFAULT true NOT NULL,
	"email_fees" boolean DEFAULT true NOT NULL,
	"email_attendance" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_check";--> statement-breakpoint
ALTER TABLE "schools" ADD COLUMN "principal_model" text DEFAULT 'single' NOT NULL;--> statement-breakpoint
ALTER TABLE "principal_assignments" ADD CONSTRAINT "principal_assignments_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "principal_assignments" ADD CONSTRAINT "principal_assignments_school_user_id_school_users_id_fk" FOREIGN KEY ("school_user_id") REFERENCES "public"."school_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "principal_assignments" ADD CONSTRAINT "principal_assignments_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_plans" ADD CONSTRAINT "lesson_plans_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_plans" ADD CONSTRAINT "lesson_plans_teacher_id_school_users_id_fk" FOREIGN KEY ("teacher_id") REFERENCES "public"."school_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_plans" ADD CONSTRAINT "lesson_plans_section_id_sections_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."sections"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_plans" ADD CONSTRAINT "lesson_plans_subject_id_subjects_id_fk" FOREIGN KEY ("subject_id") REFERENCES "public"."subjects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_school_user_id_school_users_id_fk" FOREIGN KEY ("school_user_id") REFERENCES "public"."school_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "principal_assignments_location_id_idx" ON "principal_assignments" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "principal_assignments_location_user_idx" ON "principal_assignments" USING btree ("location_id","school_user_id");--> statement-breakpoint
CREATE INDEX "lesson_plans_location_id_idx" ON "lesson_plans" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "lesson_plans_location_teacher_week_idx" ON "lesson_plans" USING btree ("location_id","teacher_id","week_starting");--> statement-breakpoint
CREATE INDEX "lesson_plans_location_section_week_idx" ON "lesson_plans" USING btree ("location_id","section_id","week_starting");--> statement-breakpoint
CREATE UNIQUE INDEX "lesson_plans_unique_idx" ON "lesson_plans" USING btree ("teacher_id","section_id","subject_id","week_starting");--> statement-breakpoint
CREATE INDEX "notification_preferences_location_id_idx" ON "notification_preferences" USING btree ("location_id");--> statement-breakpoint
CREATE UNIQUE INDEX "notification_preferences_unique_idx" ON "notification_preferences" USING btree ("location_id","school_user_id");--> statement-breakpoint
ALTER TABLE "schools" ADD CONSTRAINT "schools_principal_model_check" CHECK ("schools"."principal_model" IN ('single', 'multiple'));--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_check" CHECK (permission IN ('users.read', 'users.write', 'admissions.read', 'admissions.write', 'students.import', 'students.promote', 'students.transfer', 'fees.read', 'fees.write', 'academics.read', 'academics.write', 'attendance.mark', 'exams.read', 'exams.write', 'exams.publish', 'results.enter', 'results.publish', 'hr.read', 'hr.write', 'payroll.read', 'payroll.write', 'comms.read', 'comms.write', 'comms.send', 'settings.read', 'settings.write', 'principals.manage', 'permissions.manage'));