-- The school and branch profile fields the creation forms now ask for.
--
-- Not a sprint. Sprint 14 is internal chat (SPRINTS.md), and this migration was
-- briefly named for it by mistake; it is a fix batch against the Sprint 2/3
-- creation surfaces and is numbered only.
--
-- Eight columns, every one of them nullable or defaulted, and nothing dropped.
-- No existing row changes behaviour and no back-fill is needed, which is the
-- whole shape of this migration:
--
--   latitude/longitude are written only when the operator picks the address on
--   a map. Typing it by hand is still allowed, so these stay null for most
--   rows and nothing may require them.
--
--   landline is a second number beside the existing `phone`, which now means
--   the mobile. `phone` is NOT re-typed or re-formatted here: whatever is in it
--   is what somebody entered, and rewriting it in a migration would silently
--   alter contact details across every tenant. The form normalises on next
--   save.
--
--   board_name is required only when curriculum_level = 'MIXED', and that is
--   enforced in the API rather than by a CHECK. A CHECK would refuse to apply
--   at all if any MIXED branch already exists without one, and this migration
--   has no way to invent a board name for a school nobody has asked.
--
--   class_levels replaces max_grade and defaults to the empty array, meaning
--   "not yet declared". max_grade is deliberately LEFT IN PLACE and left
--   populated -- see db/schema/branches.ts for why it cannot be converted
--   automatically. Nothing reads or writes it any more.
--
-- Generated by drizzle-kit against the schema files, so the snapshot in meta/
-- and this file cannot disagree. Only this header is hand-written.

ALTER TABLE "schools" ADD COLUMN "latitude" double precision;--> statement-breakpoint
ALTER TABLE "schools" ADD COLUMN "longitude" double precision;--> statement-breakpoint
ALTER TABLE "schools" ADD COLUMN "landline" text;--> statement-breakpoint
ALTER TABLE "branches" ADD COLUMN "latitude" double precision;--> statement-breakpoint
ALTER TABLE "branches" ADD COLUMN "longitude" double precision;--> statement-breakpoint
ALTER TABLE "branches" ADD COLUMN "landline" text;--> statement-breakpoint
ALTER TABLE "branches" ADD COLUMN "board_name" text;--> statement-breakpoint
ALTER TABLE "branches" ADD COLUMN "class_levels" text[] DEFAULT ARRAY[]::text[] NOT NULL;