-- 0025 — named period structures, the admission fee gate, and the parent
--        welcome marker.
--
-- Three features share one migration because they are one sprint. They share
-- nothing else; read the file as three independent parts.
--
-- Generated by drizzle-kit against the schema files, so the snapshot in meta/
-- and this file cannot disagree about the shape. Hand-edited afterwards in two
-- ways only, both of them data rather than shape, and both marked ★ below:
-- `timetable_slots.period_structure_id` is added nullable, back-filled and then
-- made NOT NULL, because the generated single statement fails on the first
-- school that already has a period; and three UPDATE statements back-fill the
-- other new columns.
--
-- ── 1. Period structures ────────────────────────────────────────────────
-- `timetable_slots` was one flat list per school, uniquely keyed on
-- (location_id, order_index). A school teaching Pre-Nursery and Class 10 on one
-- campus cannot express itself that way: the infants sit three long periods and
-- go home, the seniors sit eight short ones and take their interval an hour
-- later. Under the old key the school's second bell schedule was refused as a
-- duplicate of its first.
--
-- The back-fill is written so that no existing timetable changes by one cell:
--
--   * every school that has any slots gets one structure, named "Standard",
--     marked default;
--   * every existing slot is pointed at its own school's structure;
--   * NO grade assignments are written. An unassigned grade falls back to the
--     default, so every grade keeps the schedule it already had, and a school
--     that never opens the new screen never learns the feature exists.
--
-- ── 2. The admission fee gate ───────────────────────────────────────────
-- "A student counts as enrolled once their fee is paid." Deliberately NOT a
-- fifth value of `student_enrollments.status`: that column is what the
-- register, the promotion run, the class lists, the challan generator and nine
-- reports filter on, and a child parked outside `active` would be invisible to
-- all of them — including to the challan generator that would have produced the
-- bill they are waiting to pay. The enrolment is real; what is conditional is
-- whether it has been confirmed, and that is what `fee_status` records.
--
-- New rows default to 'outstanding'. Every existing row is back-filled to
-- 'cleared', because those children are already at school: re-opening a settled
-- admission would invent a debt and would fire a welcome email to every
-- guardian on the roll the moment any payment landed.
--
-- ── 3. The parent welcome marker ────────────────────────────────────────
-- `student_guardians.welcome_email_sent_at`, so a family with three children at
-- the school receives one welcome rather than three, and so the fee gate can be
-- re-entered by a second payment without sending a second copy. Existing
-- guardians are back-filled to now(): a null means "still owed a welcome", and
-- on deploy day that would be every guardian in every school at once. An
-- administrator can still send any of them explicitly from the student profile.

CREATE TABLE "period_structure_grades" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"period_structure_id" uuid NOT NULL,
	"grade_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "period_structures" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"is_default" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DROP INDEX "timetable_slots_location_id_order_index_idx";--> statement-breakpoint
ALTER TABLE "student_enrollments" ADD COLUMN "fee_status" text DEFAULT 'outstanding' NOT NULL;--> statement-breakpoint
ALTER TABLE "student_enrollments" ADD COLUMN "fee_cleared_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "student_guardians" ADD COLUMN "welcome_email_sent_at" timestamp with time zone;--> statement-breakpoint
-- ★ Nullable, not NOT NULL as generated. The back-fill three statements down is
-- what fills it; the column is tightened afterwards.
ALTER TABLE "timetable_slots" ADD COLUMN "period_structure_id" uuid;--> statement-breakpoint
ALTER TABLE "period_structure_grades" ADD CONSTRAINT "period_structure_grades_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "period_structure_grades" ADD CONSTRAINT "period_structure_grades_period_structure_id_period_structures_id_fk" FOREIGN KEY ("period_structure_id") REFERENCES "public"."period_structures"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "period_structure_grades" ADD CONSTRAINT "period_structure_grades_grade_id_grades_id_fk" FOREIGN KEY ("grade_id") REFERENCES "public"."grades"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "period_structures" ADD CONSTRAINT "period_structures_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "period_structure_grades_location_id_idx" ON "period_structure_grades" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "period_structure_grades_structure_id_idx" ON "period_structure_grades" USING btree ("period_structure_id");--> statement-breakpoint
CREATE UNIQUE INDEX "period_structure_grades_grade_id_idx" ON "period_structure_grades" USING btree ("grade_id");--> statement-breakpoint
CREATE INDEX "period_structures_location_id_idx" ON "period_structures" USING btree ("location_id");--> statement-breakpoint
CREATE UNIQUE INDEX "period_structures_location_id_name_idx" ON "period_structures" USING btree ("location_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "period_structures_one_default_per_location_idx" ON "period_structures" USING btree ("location_id") WHERE "period_structures"."is_default";--> statement-breakpoint

-- ★ Back-fill 1 of 3 — one "Standard" structure per school that already rings a
-- bell, then every one of that school's periods pointed at it.
INSERT INTO "period_structures" ("location_id", "name", "description", "is_default")
SELECT DISTINCT s."location_id",
	'Standard',
	'The schedule this school was already running. Rename it, or add another for the grades that keep different hours.',
	true
FROM "timetable_slots" s;
--> statement-breakpoint
UPDATE "timetable_slots" s
SET "period_structure_id" = p."id"
FROM "period_structures" p
WHERE p."location_id" = s."location_id" AND p."is_default";
--> statement-breakpoint
ALTER TABLE "timetable_slots" ALTER COLUMN "period_structure_id" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "timetable_slots" ADD CONSTRAINT "timetable_slots_period_structure_id_period_structures_id_fk" FOREIGN KEY ("period_structure_id") REFERENCES "public"."period_structures"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "student_enrollments_location_fee_status_idx" ON "student_enrollments" USING btree ("location_id","fee_status");--> statement-breakpoint
CREATE INDEX "timetable_slots_period_structure_id_idx" ON "timetable_slots" USING btree ("period_structure_id");--> statement-breakpoint
CREATE UNIQUE INDEX "timetable_slots_structure_order_index_idx" ON "timetable_slots" USING btree ("period_structure_id","order_index");--> statement-breakpoint

-- ★ Back-fill 2 of 3 — everyone already on the roll is already at school. Only
-- students admitted from here on start outstanding. Runs before the CHECK so
-- the constraint is validated against the settled data.
UPDATE "student_enrollments" SET "fee_status" = 'cleared', "fee_cleared_at" = now();
--> statement-breakpoint
ALTER TABLE "student_enrollments" ADD CONSTRAINT "student_enrollments_fee_status_check" CHECK ("student_enrollments"."fee_status" IN ('outstanding', 'cleared'));--> statement-breakpoint

-- ★ Back-fill 3 of 3 — no mail-out to the existing parent body on deploy day.
UPDATE "student_guardians" SET "welcome_email_sent_at" = now();
