-- 0026 — the guardian CNIC becomes an identity key, and "Other" gets a reason.
--
-- Generated by drizzle-kit against the schema files, so the snapshot in meta/
-- and this file cannot disagree about the shape. Hand-edited afterwards in one
-- way only, marked ★ below: a data back-fill that canonicalises the CNICs
-- already in the column.
--
-- ── Why this migration exists ───────────────────────────────────────────
-- Nothing in this product linked one student to another. "Sibling" was derived
-- in exactly one place — `lib/family-challans.ts` — by grouping open challans
-- on the primary guardian's *phone number*, and it was derived nowhere else, so
-- the only screen in the entire system that knew two children were related was
-- the family voucher screen.
--
-- Phone is the wrong key for that and always was. It is a household's number,
-- not a person's: two unrelated guardians on one handset read as one family,
-- and a couple who each gave a different number for the same children read as
-- two. A CNIC is issued once, to one person, for life.
--
-- So `student_guardians.cnic` stops being a note somebody may or may not have
-- filled in and becomes the key that answers "are these two children
-- siblings" — see `lib/siblings.ts` for the full rule, including why the phone
-- number still counts alongside it rather than being replaced by it.
--
-- ── 1. relationship_other ───────────────────────────────────────────────
-- `relationship` has five fixed values, one of which is `other`, and `other`
-- on its own records nothing a teacher ringing the number could use. The new
-- column carries the school's own words — "paternal uncle", "sponsor" — and is
-- required by the API whenever the relationship is `other`.
--
-- Nullable, and deliberately without a CHECK constraint tying it to
-- `relationship`. Rows written before today are legitimate history; a
-- constraint would refuse the next unrelated write to any of them, which is a
-- migration that breaks editing a phone number in order to enforce a rule
-- about a field nobody touched.
--
-- ── 2. Two indexes ──────────────────────────────────────────────────────
-- (location_id, cnic) and (location_id, phone) are the two entry points of the
-- sibling lookup and of the enrolment form's guardian prefill. Both run on a
-- screen an admissions clerk is waiting on, and without these both are a
-- sequential scan of every guardian in the school.
--
-- ── 3. ★ The CNIC back-fill ─────────────────────────────────────────────
-- The column has been free text since Sprint 4 and was collected by four
-- different `<Input>`s, none of which masked or validated it. It therefore
-- holds `4210112345671`, `42101-1234567-1` and `42101 1234567 1` — three
-- spellings of one number, which as an identity key are three different
-- people.
--
-- Every value carrying exactly thirteen digits is rewritten to the canonical
-- `42101-1234567-1`, which is precisely what `normalizeCnic` in
-- `lib/national-id.ts` does and is the only spelling anything writes from now
-- on.
--
-- Anything else — eleven digits, a passport number somebody typed in the wrong
-- box, a note — is LEFT EXACTLY AS IT IS. Guessing at a malformed identity
-- number is how you invent a relationship between two children who are not
-- related, and this migration must not be capable of that. Those rows simply
-- do not participate in CNIC matching; `lib/siblings.ts` re-normalises on read
-- and drops what it cannot canonicalise, so a partial number can never match
-- another partial number by string equality.

ALTER TABLE "student_guardians" ADD COLUMN "relationship_other" text;--> statement-breakpoint
CREATE INDEX "student_guardians_location_cnic_idx" ON "student_guardians" USING btree ("location_id","cnic");--> statement-breakpoint
CREATE INDEX "student_guardians_location_phone_idx" ON "student_guardians" USING btree ("location_id","phone");--> statement-breakpoint

-- ★ Hand-added: canonicalise the CNICs already in the column.
UPDATE "student_guardians"
SET "cnic" =
  substring(regexp_replace("cnic", '\D', '', 'g') from 1 for 5) || '-' ||
  substring(regexp_replace("cnic", '\D', '', 'g') from 6 for 7) || '-' ||
  substring(regexp_replace("cnic", '\D', '', 'g') from 13 for 1)
WHERE "cnic" IS NOT NULL
  AND length(regexp_replace("cnic", '\D', '', 'g')) = 13
  AND "cnic" <> (
    substring(regexp_replace("cnic", '\D', '', 'g') from 1 for 5) || '-' ||
    substring(regexp_replace("cnic", '\D', '', 'g') from 6 for 7) || '-' ||
    substring(regexp_replace("cnic", '\D', '', 'g') from 13 for 1)
  );--> statement-breakpoint

-- ★ Hand-added: an empty string is not a CNIC, and as an identity key it is the
-- worst possible value — every guardian who left the field blank would match
-- every other guardian who left it blank. `readOptionalString` returns null for
-- these now; this clears the ones written before it did.
UPDATE "student_guardians" SET "cnic" = NULL WHERE trim("cnic") = '';
