-- Sprint 13.5 -- Accounting: the ledger, expenses, and per-staff cash.
--
-- Six tables and one column, and the column is the point of the sprint:
-- fee_payments.ledger_transaction_id is what makes money the school has
-- already taken part of the same books as the money it spends.
--
-- ── APPEND-ONLY ─────────────────────────────────────────────────────────
-- ledger_transactions and ledger_entries are never updated and never deleted,
-- by this application or by anybody reading this file later. A correction is a
-- second transaction whose lines are the mirror of the first, carrying
-- reverses_transaction_id, and both stay in the book. Sprint 16's parent wallet
-- and Sprint 20's POS post here, so the rule has to hold before real money
-- arrives rather than be retrofitted underneath it.
--
-- ── Income is recognised when the money is received, not when it is billed ──
-- A fee payment posts: debit the account the money landed in, credit 4000 Fee
-- Income. Raising a challan posts nothing.
--
-- That is a cash-basis decision and it is deliberate. The accrual alternative
-- -- debit 1100 Fees Receivable on issue, clear it on payment -- would put
-- eight hundred transactions in the day book every time a school bulk-generates
-- a month's challans, and would give the school two answers to "how much is
-- outstanding": the ledger's, and the fee module's. The fee module's is the one
-- with a challan number attached to every rupee of it, so it stays
-- authoritative and the aged-debt report keeps reading it.
--
-- 1100 Fees Receivable is still seeded, because a school moving its books in
-- here needs somewhere to put the fees that were already owed on the day it
-- started. It is reached by journal entry, not by the fee module.
--
-- ── Per-staff cash accounts ─────────────────────────────────────────────
-- A cash payment does not land in the office safe. It lands in the drawer of
-- whoever took it, and that is a different fact. Each person who takes money
-- gets their own asset account (ledger_accounts.owner_user_id); settling is a
-- transaction moving the balance to office cash, and their balance in between
-- is what they owe the school right now. See db/schema/cash-settlements.ts.
--
-- ── The permission CHECK ────────────────────────────────────────────────
-- Dropped and recreated with accounting.read / .write / .settle, which is what
-- adding any permission key costs -- the constraint is generated from the
-- PERMISSIONS array in lib/permissions.ts (STATE.md §5aa).
--
-- ── The three hand-written parts ────────────────────────────────────────
-- Everything above the "SEED" divider is generated by drizzle-kit from the
-- schema files, so this file and the snapshot in meta/ cannot disagree.
-- Everything below it is hand-written and is the part that has to be read:
-- the chart of accounts every existing school gets, its expense categories,
-- and the backfill of every fee payment ever recorded into the ledger.
--
-- The backfill is guarded rather than assumed. It posts only for schools that
-- came out of the seed with a Fee Income account, and only for payments that
-- do not already carry a posting -- so running it twice writes nothing the
-- second time.

CREATE TABLE "ledger_accounts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"branch_id" uuid,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"description" text,
	"system_key" text,
	"owner_user_id" uuid,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ledger_accounts_type_check" CHECK (type IN ('asset', 'liability', 'equity', 'income', 'expense')),
	CONSTRAINT "ledger_accounts_code_check" CHECK ("ledger_accounts"."code" ~ '^[0-9]{3,8}$')
);
--> statement-breakpoint
CREATE TABLE "ledger_entries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"transaction_id" uuid NOT NULL,
	"account_id" uuid NOT NULL,
	"debit" numeric(14, 2) DEFAULT '0' NOT NULL,
	"credit" numeric(14, 2) DEFAULT '0' NOT NULL,
	"memo" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ledger_entries_debit_check" CHECK ("ledger_entries"."debit" >= 0),
	CONSTRAINT "ledger_entries_credit_check" CHECK ("ledger_entries"."credit" >= 0),
	CONSTRAINT "ledger_entries_one_side_check" CHECK (("ledger_entries"."debit" = 0) <> ("ledger_entries"."credit" = 0))
);
--> statement-breakpoint
CREATE TABLE "ledger_transactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"branch_id" uuid,
	"entry_date" date NOT NULL,
	"memo" text NOT NULL,
	"source" text NOT NULL,
	"source_id" uuid,
	"reference_number" text,
	"reverses_transaction_id" uuid,
	"created_by_uid" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ledger_transactions_source_check" CHECK (source IN ('fee_payment', 'expense', 'settlement', 'payroll', 'opening_balance', 'manual', 'reversal'))
);
--> statement-breakpoint
CREATE TABLE "expense_categories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"name" text NOT NULL,
	"ledger_account_id" uuid NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "expenses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"branch_id" uuid,
	"category_id" uuid NOT NULL,
	"paid_from_account_id" uuid NOT NULL,
	"amount" numeric(14, 2) NOT NULL,
	"expense_date" date NOT NULL,
	"payee" text,
	"reference_number" text,
	"attachment_url" text,
	"notes" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_by_uid" text NOT NULL,
	"approved_by" uuid,
	"approved_at" timestamp with time zone,
	"rejection_reason" text,
	"ledger_transaction_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "expenses_amount_check" CHECK ("expenses"."amount" > 0),
	CONSTRAINT "expenses_status_check" CHECK (status IN ('draft', 'approved', 'rejected')),
	CONSTRAINT "expenses_posting_check" CHECK (("expenses"."status" = 'approved') = ("expenses"."ledger_transaction_id" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "cash_settlements" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"staff_user_id" uuid NOT NULL,
	"from_account_id" uuid NOT NULL,
	"to_account_id" uuid NOT NULL,
	"amount" numeric(14, 2) NOT NULL,
	"expected_amount" numeric(14, 2) NOT NULL,
	"settlement_date" date NOT NULL,
	"received_by_uid" text NOT NULL,
	"reference_number" text,
	"notes" text,
	"ledger_transaction_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cash_settlements_amount_check" CHECK ("cash_settlements"."amount" > 0),
	CONSTRAINT "cash_settlements_accounts_differ_check" CHECK ("cash_settlements"."from_account_id" <> "cash_settlements"."to_account_id")
);
--> statement-breakpoint
ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_check";--> statement-breakpoint
ALTER TABLE "fee_payments" ADD COLUMN "ledger_transaction_id" uuid;--> statement-breakpoint
ALTER TABLE "ledger_accounts" ADD CONSTRAINT "ledger_accounts_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_accounts" ADD CONSTRAINT "ledger_accounts_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_accounts" ADD CONSTRAINT "ledger_accounts_owner_user_id_school_users_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."school_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_transaction_id_ledger_transactions_id_fk" FOREIGN KEY ("transaction_id") REFERENCES "public"."ledger_transactions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_account_id_ledger_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_transactions" ADD CONSTRAINT "ledger_transactions_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_transactions" ADD CONSTRAINT "ledger_transactions_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_transactions" ADD CONSTRAINT "ledger_transactions_reverses_transaction_id_ledger_transactions_id_fk" FOREIGN KEY ("reverses_transaction_id") REFERENCES "public"."ledger_transactions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_categories" ADD CONSTRAINT "expense_categories_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_categories" ADD CONSTRAINT "expense_categories_ledger_account_id_ledger_accounts_id_fk" FOREIGN KEY ("ledger_account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_category_id_expense_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."expense_categories"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_paid_from_account_id_ledger_accounts_id_fk" FOREIGN KEY ("paid_from_account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_approved_by_school_users_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."school_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_ledger_transaction_id_ledger_transactions_id_fk" FOREIGN KEY ("ledger_transaction_id") REFERENCES "public"."ledger_transactions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cash_settlements" ADD CONSTRAINT "cash_settlements_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cash_settlements" ADD CONSTRAINT "cash_settlements_staff_user_id_school_users_id_fk" FOREIGN KEY ("staff_user_id") REFERENCES "public"."school_users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cash_settlements" ADD CONSTRAINT "cash_settlements_from_account_id_ledger_accounts_id_fk" FOREIGN KEY ("from_account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cash_settlements" ADD CONSTRAINT "cash_settlements_to_account_id_ledger_accounts_id_fk" FOREIGN KEY ("to_account_id") REFERENCES "public"."ledger_accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cash_settlements" ADD CONSTRAINT "cash_settlements_ledger_transaction_id_ledger_transactions_id_fk" FOREIGN KEY ("ledger_transaction_id") REFERENCES "public"."ledger_transactions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ledger_accounts_location_id_idx" ON "ledger_accounts" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "ledger_accounts_owner_user_id_idx" ON "ledger_accounts" USING btree ("owner_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "ledger_accounts_location_code_idx" ON "ledger_accounts" USING btree ("location_id","code");--> statement-breakpoint
CREATE UNIQUE INDEX "ledger_accounts_location_system_key_idx" ON "ledger_accounts" USING btree ("location_id","system_key") WHERE system_key IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "ledger_accounts_location_owner_idx" ON "ledger_accounts" USING btree ("location_id","owner_user_id") WHERE owner_user_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "ledger_entries_location_id_idx" ON "ledger_entries" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "ledger_entries_transaction_id_idx" ON "ledger_entries" USING btree ("transaction_id");--> statement-breakpoint
CREATE INDEX "ledger_entries_location_account_idx" ON "ledger_entries" USING btree ("location_id","account_id");--> statement-breakpoint
CREATE INDEX "ledger_transactions_location_id_idx" ON "ledger_transactions" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "ledger_transactions_location_date_idx" ON "ledger_transactions" USING btree ("location_id","entry_date");--> statement-breakpoint
CREATE INDEX "ledger_transactions_source_idx" ON "ledger_transactions" USING btree ("location_id","source","source_id");--> statement-breakpoint
CREATE INDEX "ledger_transactions_reverses_idx" ON "ledger_transactions" USING btree ("reverses_transaction_id");--> statement-breakpoint
CREATE INDEX "expense_categories_location_id_idx" ON "expense_categories" USING btree ("location_id");--> statement-breakpoint
CREATE UNIQUE INDEX "expense_categories_location_name_idx" ON "expense_categories" USING btree ("location_id",lower("name"));--> statement-breakpoint
CREATE INDEX "expenses_location_id_idx" ON "expenses" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "expenses_location_date_idx" ON "expenses" USING btree ("location_id","expense_date");--> statement-breakpoint
CREATE INDEX "expenses_location_status_idx" ON "expenses" USING btree ("location_id","status");--> statement-breakpoint
CREATE INDEX "expenses_category_id_idx" ON "expenses" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "cash_settlements_location_id_idx" ON "cash_settlements" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "cash_settlements_location_date_idx" ON "cash_settlements" USING btree ("location_id","settlement_date");--> statement-breakpoint
CREATE INDEX "cash_settlements_staff_user_id_idx" ON "cash_settlements" USING btree ("staff_user_id");--> statement-breakpoint
ALTER TABLE "fee_payments" ADD CONSTRAINT "fee_payments_ledger_transaction_id_ledger_transactions_id_fk" FOREIGN KEY ("ledger_transaction_id") REFERENCES "public"."ledger_transactions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_check" CHECK (permission IN ('users.read', 'users.write', 'admissions.read', 'admissions.write', 'students.import', 'students.promote', 'students.transfer', 'fees.read', 'fees.write', 'academics.read', 'academics.write', 'attendance.mark', 'exams.read', 'exams.write', 'exams.publish', 'results.enter', 'results.publish', 'hr.read', 'hr.write', 'payroll.read', 'payroll.write', 'comms.read', 'comms.write', 'comms.send', 'settings.read', 'settings.write', 'principals.manage', 'permissions.manage', 'accounting.read', 'accounting.write', 'accounting.settle'));
--> statement-breakpoint
-- ═══════════════════════════════════════════════════════════════════════════
-- SEED -- hand-written from here down. See the header.
-- ═══════════════════════════════════════════════════════════════════════════

-- Every existing school gets the chart of accounts a new one is seeded with.
-- Kept deliberately short: twelve heads a bursar reads in one screen and
-- extends when they need to, rather than the eighty-line template an accounting
-- package ships with, of which a school uses nine and is confused by the rest.
-- The list is `DEFAULT_CHART` in lib/accounting.ts and the two must stay in
-- step -- scripts/check-accounting.ts asserts that they do.
INSERT INTO "ledger_accounts" ("location_id", "code", "name", "type", "system_key", "description")
SELECT
	s."location_id",
	seed."code",
	seed."name",
	seed."type",
	seed."system_key",
	seed."description"
FROM "schools" s
CROSS JOIN (VALUES
	('1000', 'Cash in Hand',          'asset',     'cash_in_hand',     'The office drawer. Where a cash fee payment lands and where a counter settles to.'),
	('1010', 'Bank Account',          'asset',     'bank',             'Money at the bank. Where a fee paid by transfer lands.'),
	('1020', 'Cheques in Hand',       'asset',     'cheques_in_hand',  'Cheques received and not yet cleared. Held separately from Bank because a cheque is not money until it clears.'),
	('1100', 'Fees Receivable',       'asset',     'fees_receivable',  'Fees billed on a challan and not yet received.'),
	('2000', 'Accounts Payable',      'liability', 'accounts_payable', 'Bills the school has accepted and not yet paid.'),
	('3000', 'Opening Balance',       'equity',    'opening_balance',  'The other side of every opening figure entered when the school started keeping books here.'),
	('4000', 'Fee Income',            'income',    'fee_income',       'Tuition and every other charge raised on a challan.'),
	('4900', 'Other Income',          'income',    'other_income',     'Donations, hall hire, anything earned that is not a fee.'),
	('5000', 'Salaries & Wages',      'expense',   'salary_expense',   'The staff bill. Payroll posts here.'),
	('5100', 'Rent',                  'expense',   NULL,               'Building rent for every campus.'),
	('5200', 'Utilities',             'expense',   NULL,               'Electricity, gas, water, internet.'),
	('5300', 'Teaching Materials',    'expense',   NULL,               'Books, stationery, lab and sports consumables.'),
	('5400', 'Transport & Fuel',      'expense',   NULL,               'School vans, fuel and their upkeep.'),
	('5500', 'Repairs & Maintenance', 'expense',   NULL,               'Building, furniture and equipment repairs.'),
	('5900', 'Other Expenses',        'expense',   'other_expense',    'Anything spent that does not belong under a head above.')
) AS seed("code", "name", "type", "system_key", "description")
ON CONFLICT DO NOTHING;--> statement-breakpoint

-- The expense categories that go with it. A category is the word a clerk picks
-- from; the account is where the money lands, which is why two categories may
-- point at one head -- "Van Fuel" and "Van Repairs" are both Transport & Fuel.
INSERT INTO "expense_categories" ("location_id", "name", "ledger_account_id")
SELECT
	account."location_id",
	seed."name",
	account."id"
FROM (VALUES
	('Rent',                    '5100'),
	('Electricity',             '5200'),
	('Gas & Water',             '5200'),
	('Internet & Phone',        '5200'),
	('Stationery & Printing',   '5300'),
	('Lab & Sports Supplies',   '5300'),
	('Van Fuel',                '5400'),
	('Van Repairs',             '5400'),
	('Building Repairs',        '5500'),
	('Furniture & Equipment',   '5500'),
	('Miscellaneous',           '5900')
) AS seed("name", "account_code")
JOIN "ledger_accounts" account ON account."code" = seed."account_code"
ON CONFLICT DO NOTHING;--> statement-breakpoint

-- ── The backfill ────────────────────────────────────────────────────────
-- Every fee payment ever recorded becomes a posting. Without this the ledger
-- opens empty at a school that has been taking money for a year, its Cash in
-- Hand reads zero, and the first person to look at a balance sheet concludes
-- the module does not work.
--
-- entry_date is the payment date, not today: a backfill dated the day of the
-- migration would put a year of takings on one afternoon's day book.
INSERT INTO "ledger_transactions" (
	"location_id", "entry_date", "memo", "source", "source_id",
	"reference_number", "created_by_uid", "created_at"
)
SELECT
	payment."location_id",
	payment."payment_date",
	'Fee payment (backfilled from the fee module)',
	'fee_payment',
	payment."id",
	payment."reference_number",
	payment."collected_by_uid",
	payment."created_at"
FROM "fee_payments" payment
WHERE payment."ledger_transaction_id" IS NULL
	AND EXISTS (
		SELECT 1 FROM "ledger_accounts" a
		WHERE a."location_id" = payment."location_id" AND a."system_key" = 'fee_income'
	);--> statement-breakpoint

-- Two lines each: the account the money landed in, and Fee Income. A cheque
-- goes to 1020 rather than 1010 -- a cheque is not money until it clears, and a
-- school counting it as bank balance will overdraw on one that bounces.
--
-- Backfilled cash goes to office cash rather than to the collector's own
-- account: per-staff accounts do not exist yet at the moment this runs, and
-- inventing one retrospectively would open every clerk's balance with a year of
-- takings they settled long ago.
INSERT INTO "ledger_entries" (
	"location_id", "transaction_id", "account_id", "debit", "credit", "memo", "created_at"
)
SELECT
	txn."location_id",
	txn."id",
	side."account_id",
	side."debit",
	side."credit",
	side."memo",
	txn."created_at"
FROM "ledger_transactions" txn
JOIN "fee_payments" payment ON payment."id" = txn."source_id"
JOIN LATERAL (
	SELECT
		landing."id" AS "account_id",
		payment."amount" AS "debit",
		0::numeric AS "credit",
		'Money received'::text AS "memo"
	FROM "ledger_accounts" landing
	WHERE landing."location_id" = txn."location_id"
		AND landing."system_key" = CASE payment."payment_method"
			WHEN 'bank_transfer' THEN 'bank'
			WHEN 'cheque' THEN 'cheques_in_hand'
			ELSE 'cash_in_hand'
		END
	UNION ALL
	SELECT
		income."id",
		0::numeric,
		payment."amount",
		'Fee income'::text
	FROM "ledger_accounts" income
	WHERE income."location_id" = txn."location_id"
		AND income."system_key" = 'fee_income'
) side ON TRUE
WHERE txn."source" = 'fee_payment'
	AND NOT EXISTS (
		SELECT 1 FROM "ledger_entries" e WHERE e."transaction_id" = txn."id"
	);--> statement-breakpoint

-- And the link back, which is what stops the backfill running twice.
UPDATE "fee_payments" payment
SET "ledger_transaction_id" = txn."id"
FROM "ledger_transactions" txn
WHERE txn."source" = 'fee_payment'
	AND txn."source_id" = payment."id"
	AND payment."ledger_transaction_id" IS NULL;
