-- Sprint 14 -- Exam terms, per-grade datesheets, promotion criteria, results.
--
-- Seven tables, eleven columns and one relaxed CHECK. The shape of the sprint
-- is that a term stops being a window with exams hung off it and becomes a
-- *heading* over one or more datesheets, because the infant school and the
-- senior school do not sit "First Term" on the same days and never did.
--
-- ── Why exam_terms.start_date became nullable ───────────────────────────
-- The authoritative dates moved down to exam_schedules, where they can differ
-- per grade. The term keeps an optional envelope for calendar views, and every
-- term that exists today keeps the dates it was created with -- nothing is
-- cleared. Where it is blank the UI shows the earliest start and the latest end
-- across the term's schedules.
--
-- ── Why exam_schedule_grades carries term_id ────────────────────────────
-- The rule is "a grade sits at most one datesheet per term", and that is a
-- uniqueness constraint spanning the term, not the schedule. Without the column
-- it is an application check that two concurrent requests both pass, leaving a
-- class on two datesheets and the generate step writing two sets of papers for
-- the same children. Archiving a schedule MUST archive its grade rows in the
-- same transaction or the grade stays locked out by an index nobody can see.
--
-- ── Why exam_results_marks_check had to be relaxed ──────────────────────
-- The old rule was "absent with no mark, or present with a mark". In descriptor
-- mode the child was present and there is no mark, so the only valid descriptor
-- row was unwritable. The new rule keeps the fact that mattered -- an absence
-- never carries a mark -- and drops the one that stopped holding the moment a
-- result could be a word instead of a number.
--
-- exam_subjects.max_marks is deliberately NOT relaxed. It stays NOT NULL with
-- its > 0 CHECK, and the generate step writes 1/0 for a descriptor paper that
-- no descriptor code path ever reads. Relaxing it would put a null denominator
-- inside every percentage the marks path computes, to save two literals.
--
-- ── student_term_results is not promotion_runs ──────────────────────────
-- promotion_runs is enrolment plumbing: which section a child sits in next
-- September. student_term_results.final_status is the academic judgement: did
-- this child pass. Different facts, different people, different moments. This
-- migration does not merge them and no later one should.
--
-- ── The permission CHECK ────────────────────────────────────────────────
-- Dropped and recreated with results.promotion, which is what adding any
-- permission key costs -- the constraint is generated from the PERMISSIONS
-- array in lib/permissions.ts (STATE.md §5aa). No role_permissions rows are
-- inserted: that table holds *overrides*, and seeding it would freeze the three
-- roles' access at today's answer. The grant lives in DEFAULT_ROLE_PERMISSIONS,
-- exactly as 0027 did for the three accounting keys.
--
-- ── The four hand-written parts ─────────────────────────────────────────
-- Everything between the PRE-FLIGHT and SEED dividers is generated by
-- drizzle-kit from the schema files, so this file and the snapshot in meta/
-- cannot disagree. The two hand-written blocks are:
--
--   PRE-FLIGHT  trims any term name longer than the new 50-character CHECK
--               allows. The API used to accept 80, so a school that used them
--               would otherwise have this migration fail on ALTER TABLE ...
--               ADD CONSTRAINT with a message naming neither the row nor why.
--   SEED        backfills exam_terms.sequence_order from the dates each term
--               already has, and gives every existing school the four default
--               result sub-categories a new school is seeded with.
--
-- Both are idempotent. Running this twice writes nothing the second time.

-- ═══════════════════════════════════════════════════════════════════════════
-- PRE-FLIGHT -- hand-written. Must run before the CHECK below is added.
-- ═══════════════════════════════════════════════════════════════════════════

-- A term named at 80 characters is a term somebody pasted a sentence into, and
-- the first 50 of it is the part that identifies it. Trimmed rather than
-- refused: failing the migration would leave the whole sprint unapplied over
-- one row of somebody's punctuation.
UPDATE "exam_terms"
SET "name" = btrim(left(btrim("name"), 50))
WHERE char_length(btrim("name")) > 50;--> statement-breakpoint

-- ═══════════════════════════════════════════════════════════════════════════
-- GENERATED -- drizzle-kit from db/schema. See the header.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE "result_subcategories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"label" text NOT NULL,
	"color_hex" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"archived_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "result_subcategories_color_check" CHECK ("result_subcategories"."color_hex" IS NULL OR "result_subcategories"."color_hex" ~ '^#[0-9A-Fa-f]{6}$'),
	CONSTRAINT "result_subcategories_label_length_check" CHECK (char_length(btrim("result_subcategories"."label")) BETWEEN 1 AND 40)
);
--> statement-breakpoint
CREATE TABLE "school_exam_settings" (
	"location_id" text PRIMARY KEY NOT NULL,
	"color_coding_enabled" boolean DEFAULT true NOT NULL,
	"teachers_can_view_legacy_results" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "exam_schedules" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"term_id" uuid NOT NULL,
	"name" text NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date,
	"archived_at" timestamp with time zone,
	"archived_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "exam_schedules_dates_check" CHECK ("exam_schedules"."end_date" IS NULL OR "exam_schedules"."end_date" >= "exam_schedules"."start_date"),
	CONSTRAINT "exam_schedules_name_length_check" CHECK (char_length(btrim("exam_schedules"."name")) BETWEEN 1 AND 50)
);
--> statement-breakpoint
CREATE TABLE "exam_schedule_grades" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"schedule_id" uuid NOT NULL,
	"term_id" uuid NOT NULL,
	"grade_id" uuid NOT NULL,
	"archived_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "exam_schedule_subjects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"schedule_id" uuid NOT NULL,
	"subject_id" uuid NOT NULL,
	"exam_date" date NOT NULL,
	"start_time" text,
	"duration_minutes" integer,
	"max_marks" numeric(6, 2),
	"passing_marks" numeric(6, 2),
	"order_index" integer DEFAULT 0 NOT NULL,
	"archived_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "exam_schedule_subjects_duration_check" CHECK ("exam_schedule_subjects"."duration_minutes" IS NULL OR ("exam_schedule_subjects"."duration_minutes" > 0 AND "exam_schedule_subjects"."duration_minutes" <= 600)),
	CONSTRAINT "exam_schedule_subjects_marks_check" CHECK (("exam_schedule_subjects"."max_marks" IS NULL AND "exam_schedule_subjects"."passing_marks" IS NULL) OR ("exam_schedule_subjects"."max_marks" > 0 AND "exam_schedule_subjects"."passing_marks" >= 0 AND "exam_schedule_subjects"."passing_marks" <= "exam_schedule_subjects"."max_marks"))
);
--> statement-breakpoint
CREATE TABLE "grade_promotion_criteria" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"academic_year_id" uuid NOT NULL,
	"grade_id" uuid NOT NULL,
	"mechanism" text NOT NULL,
	"grading_scheme_id" uuid,
	"min_overall_percentage" numeric(5, 2),
	"max_failed_subjects" integer,
	"failing_subcategory_id" uuid,
	"max_failing_subjects" integer,
	"min_attendance_percentage" numeric(5, 2),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "grade_promotion_criteria_mechanism_check" CHECK ("grade_promotion_criteria"."mechanism" IN ('marks_grades', 'descriptors')),
	CONSTRAINT "grade_promotion_criteria_pct_check" CHECK (("grade_promotion_criteria"."min_overall_percentage" IS NULL OR ("grade_promotion_criteria"."min_overall_percentage" >= 0 AND "grade_promotion_criteria"."min_overall_percentage" <= 100)) AND ("grade_promotion_criteria"."min_attendance_percentage" IS NULL OR ("grade_promotion_criteria"."min_attendance_percentage" >= 0 AND "grade_promotion_criteria"."min_attendance_percentage" <= 100)))
);
--> statement-breakpoint
CREATE TABLE "student_term_results" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_id" text NOT NULL,
	"term_id" uuid NOT NULL,
	"student_profile_id" uuid NOT NULL,
	"section_id" uuid NOT NULL,
	"grade_id" uuid NOT NULL,
	"academic_year_id" uuid NOT NULL,
	"mechanism" text NOT NULL,
	"overall_percentage" numeric(5, 2),
	"overall_grade_label" text,
	"overall_subcategory_id" uuid,
	"computed_status" text NOT NULL,
	"final_status" text NOT NULL,
	"override_reason" text,
	"overridden_by" uuid,
	"overridden_at" timestamp with time zone,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "student_term_results_status_check" CHECK ("student_term_results"."computed_status" IN ('promoted', 'not_promoted') AND "student_term_results"."final_status" IN ('promoted', 'not_promoted')),
	CONSTRAINT "student_term_results_override_check" CHECK (("student_term_results"."final_status" = "student_term_results"."computed_status" AND "student_term_results"."override_reason" IS NULL) OR ("student_term_results"."final_status" <> "student_term_results"."computed_status" AND "student_term_results"."override_reason" IS NOT NULL AND char_length(btrim("student_term_results"."override_reason")) >= 10))
);
--> statement-breakpoint
ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_check";--> statement-breakpoint
ALTER TABLE "exam_results" DROP CONSTRAINT "exam_results_marks_check";--> statement-breakpoint
DROP INDEX "exam_terms_location_year_name_idx";--> statement-breakpoint
ALTER TABLE "exam_terms" ALTER COLUMN "start_date" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "exam_terms" ALTER COLUMN "end_date" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "staff" ADD COLUMN "is_class_teacher" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "sections" ADD COLUMN "class_teacher_id" uuid;--> statement-breakpoint
ALTER TABLE "exam_terms" ADD COLUMN "sequence_order" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "exam_terms" ADD COLUMN "archived_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "exam_terms" ADD COLUMN "archived_by" uuid;--> statement-breakpoint
ALTER TABLE "exams" ADD COLUMN "schedule_id" uuid;--> statement-breakpoint
ALTER TABLE "exams" ADD COLUMN "archived_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "exam_subjects" ADD COLUMN "schedule_subject_id" uuid;--> statement-breakpoint
ALTER TABLE "exam_subjects" ADD COLUMN "archived_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "exam_results" ADD COLUMN "subcategory_id" uuid;--> statement-breakpoint
ALTER TABLE "result_subcategories" ADD CONSTRAINT "result_subcategories_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "school_exam_settings" ADD CONSTRAINT "school_exam_settings_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_schedules" ADD CONSTRAINT "exam_schedules_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_schedules" ADD CONSTRAINT "exam_schedules_term_id_exam_terms_id_fk" FOREIGN KEY ("term_id") REFERENCES "public"."exam_terms"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_schedules" ADD CONSTRAINT "exam_schedules_archived_by_school_users_id_fk" FOREIGN KEY ("archived_by") REFERENCES "public"."school_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_schedule_grades" ADD CONSTRAINT "exam_schedule_grades_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_schedule_grades" ADD CONSTRAINT "exam_schedule_grades_schedule_id_exam_schedules_id_fk" FOREIGN KEY ("schedule_id") REFERENCES "public"."exam_schedules"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_schedule_grades" ADD CONSTRAINT "exam_schedule_grades_term_id_exam_terms_id_fk" FOREIGN KEY ("term_id") REFERENCES "public"."exam_terms"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_schedule_grades" ADD CONSTRAINT "exam_schedule_grades_grade_id_grades_id_fk" FOREIGN KEY ("grade_id") REFERENCES "public"."grades"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_schedule_subjects" ADD CONSTRAINT "exam_schedule_subjects_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_schedule_subjects" ADD CONSTRAINT "exam_schedule_subjects_schedule_id_exam_schedules_id_fk" FOREIGN KEY ("schedule_id") REFERENCES "public"."exam_schedules"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_schedule_subjects" ADD CONSTRAINT "exam_schedule_subjects_subject_id_subjects_id_fk" FOREIGN KEY ("subject_id") REFERENCES "public"."subjects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grade_promotion_criteria" ADD CONSTRAINT "grade_promotion_criteria_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grade_promotion_criteria" ADD CONSTRAINT "grade_promotion_criteria_academic_year_id_academic_years_id_fk" FOREIGN KEY ("academic_year_id") REFERENCES "public"."academic_years"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grade_promotion_criteria" ADD CONSTRAINT "grade_promotion_criteria_grade_id_grades_id_fk" FOREIGN KEY ("grade_id") REFERENCES "public"."grades"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grade_promotion_criteria" ADD CONSTRAINT "grade_promotion_criteria_grading_scheme_id_grading_schemes_id_fk" FOREIGN KEY ("grading_scheme_id") REFERENCES "public"."grading_schemes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grade_promotion_criteria" ADD CONSTRAINT "grade_promotion_criteria_failing_subcategory_id_result_subcategories_id_fk" FOREIGN KEY ("failing_subcategory_id") REFERENCES "public"."result_subcategories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_term_results" ADD CONSTRAINT "student_term_results_location_id_schools_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."schools"("location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_term_results" ADD CONSTRAINT "student_term_results_term_id_exam_terms_id_fk" FOREIGN KEY ("term_id") REFERENCES "public"."exam_terms"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_term_results" ADD CONSTRAINT "student_term_results_student_profile_id_student_profiles_id_fk" FOREIGN KEY ("student_profile_id") REFERENCES "public"."student_profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_term_results" ADD CONSTRAINT "student_term_results_section_id_sections_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."sections"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_term_results" ADD CONSTRAINT "student_term_results_grade_id_grades_id_fk" FOREIGN KEY ("grade_id") REFERENCES "public"."grades"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_term_results" ADD CONSTRAINT "student_term_results_academic_year_id_academic_years_id_fk" FOREIGN KEY ("academic_year_id") REFERENCES "public"."academic_years"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_term_results" ADD CONSTRAINT "student_term_results_overall_subcategory_id_result_subcategories_id_fk" FOREIGN KEY ("overall_subcategory_id") REFERENCES "public"."result_subcategories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_term_results" ADD CONSTRAINT "student_term_results_overridden_by_school_users_id_fk" FOREIGN KEY ("overridden_by") REFERENCES "public"."school_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "result_subcategories_location_idx" ON "result_subcategories" USING btree ("location_id");--> statement-breakpoint
CREATE UNIQUE INDEX "result_subcategories_location_label_idx" ON "result_subcategories" USING btree ("location_id",lower(btrim("label"))) WHERE archived_at IS NULL;--> statement-breakpoint
CREATE INDEX "exam_schedules_location_id_idx" ON "exam_schedules" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "exam_schedules_term_id_idx" ON "exam_schedules" USING btree ("term_id");--> statement-breakpoint
CREATE UNIQUE INDEX "exam_schedules_term_name_idx" ON "exam_schedules" USING btree ("term_id","name") WHERE archived_at IS NULL;--> statement-breakpoint
CREATE INDEX "exam_schedule_grades_location_id_idx" ON "exam_schedule_grades" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "exam_schedule_grades_schedule_idx" ON "exam_schedule_grades" USING btree ("schedule_id");--> statement-breakpoint
CREATE UNIQUE INDEX "exam_schedule_grades_term_grade_idx" ON "exam_schedule_grades" USING btree ("term_id","grade_id") WHERE archived_at IS NULL;--> statement-breakpoint
CREATE INDEX "exam_schedule_subjects_location_id_idx" ON "exam_schedule_subjects" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "exam_schedule_subjects_schedule_idx" ON "exam_schedule_subjects" USING btree ("schedule_id");--> statement-breakpoint
CREATE UNIQUE INDEX "exam_schedule_subjects_schedule_subject_idx" ON "exam_schedule_subjects" USING btree ("schedule_id","subject_id") WHERE archived_at IS NULL;--> statement-breakpoint
CREATE INDEX "grade_promotion_criteria_location_idx" ON "grade_promotion_criteria" USING btree ("location_id");--> statement-breakpoint
CREATE UNIQUE INDEX "grade_promotion_criteria_year_grade_idx" ON "grade_promotion_criteria" USING btree ("location_id","academic_year_id","grade_id");--> statement-breakpoint
CREATE UNIQUE INDEX "student_term_results_term_student_idx" ON "student_term_results" USING btree ("location_id","term_id","student_profile_id");--> statement-breakpoint
CREATE INDEX "student_term_results_location_student_idx" ON "student_term_results" USING btree ("location_id","student_profile_id");--> statement-breakpoint
CREATE INDEX "student_term_results_term_section_idx" ON "student_term_results" USING btree ("term_id","section_id");--> statement-breakpoint
ALTER TABLE "sections" ADD CONSTRAINT "sections_class_teacher_id_staff_id_fk" FOREIGN KEY ("class_teacher_id") REFERENCES "public"."staff"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_terms" ADD CONSTRAINT "exam_terms_archived_by_school_users_id_fk" FOREIGN KEY ("archived_by") REFERENCES "public"."school_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exams" ADD CONSTRAINT "exams_schedule_id_exam_schedules_id_fk" FOREIGN KEY ("schedule_id") REFERENCES "public"."exam_schedules"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_subjects" ADD CONSTRAINT "exam_subjects_schedule_subject_id_exam_schedule_subjects_id_fk" FOREIGN KEY ("schedule_subject_id") REFERENCES "public"."exam_schedule_subjects"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exam_results" ADD CONSTRAINT "exam_results_subcategory_id_result_subcategories_id_fk" FOREIGN KEY ("subcategory_id") REFERENCES "public"."result_subcategories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "sections_class_teacher_id_idx" ON "sections" USING btree ("class_teacher_id");--> statement-breakpoint
CREATE INDEX "exams_schedule_id_idx" ON "exams" USING btree ("schedule_id");--> statement-breakpoint
CREATE UNIQUE INDEX "exam_terms_location_year_name_idx" ON "exam_terms" USING btree ("location_id","academic_year_id","name") WHERE archived_at IS NULL;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_check" CHECK (permission IN ('users.read', 'users.write', 'admissions.read', 'admissions.write', 'students.import', 'students.promote', 'students.transfer', 'fees.read', 'fees.write', 'academics.read', 'academics.write', 'attendance.mark', 'exams.read', 'exams.write', 'exams.publish', 'results.enter', 'results.publish', 'results.promotion', 'hr.read', 'hr.write', 'payroll.read', 'payroll.write', 'comms.read', 'comms.write', 'comms.send', 'settings.read', 'settings.write', 'principals.manage', 'permissions.manage', 'accounting.read', 'accounting.write', 'accounting.settle'));--> statement-breakpoint
ALTER TABLE "exam_terms" ADD CONSTRAINT "exam_terms_name_length_check" CHECK (char_length(btrim("exam_terms"."name")) BETWEEN 1 AND 50);--> statement-breakpoint
ALTER TABLE "exam_results" ADD CONSTRAINT "exam_results_marks_check" CHECK (("exam_results"."marks_obtained" IS NULL OR "exam_results"."marks_obtained" >= 0) AND NOT ("exam_results"."is_absent" AND "exam_results"."marks_obtained" IS NOT NULL));

--> statement-breakpoint
-- ═══════════════════════════════════════════════════════════════════════════
-- SEED -- hand-written from here down. See the header.
-- ═══════════════════════════════════════════════════════════════════════════

-- sequence_order defaults to 0, which would put every existing term joint
-- first and let the list order itself arbitrarily. The order a school already
-- reads its terms in is the order of their start dates, so that is what this
-- writes: First Term, Second Term, Final Term, exactly as they were.
--
-- created_at breaks a tie between two terms that start on the same day, so the
-- result is stable rather than whatever the planner returned that afternoon.
UPDATE "exam_terms"
SET "sequence_order" = ordered."rn"
FROM (
	SELECT
		"id",
		row_number() OVER (
			PARTITION BY "location_id", "academic_year_id"
			ORDER BY "start_date", "created_at"
		) AS "rn"
	FROM "exam_terms"
) AS ordered
WHERE "exam_terms"."id" = ordered."id"
	AND "exam_terms"."sequence_order" = 0;--> statement-breakpoint

-- Every existing school gets the four sub-categories a new one is seeded with.
-- The list is DEFAULT_SUBCATEGORIES in db/schema/result-subcategories.ts and
-- lib/school-bootstrap.ts gives the same four to every school created after
-- this runs -- a school provisioned on either side of this migration has to
-- behave identically.
--
-- Green through red, best to worst, because that is the order a teacher reads a
-- picker in and a parent reads a legend in. A school that words its judgements
-- differently renames them; the point of seeding is that the descriptor screen
-- opens with something in it rather than an empty state and a shrug.
INSERT INTO "result_subcategories" ("location_id", "label", "color_hex", "sort_order")
SELECT
	s."location_id",
	seed."label",
	seed."color_hex",
	seed."sort_order"
FROM "schools" s
CROSS JOIN (VALUES
	('Exceeding',         '#22C55E', 0),
	('Satisfactory',      '#3B82F6', 1),
	('Emerging',          '#F59E0B', 2),
	('Needs Improvement', '#EF4444', 3)
) AS seed("label", "color_hex", "sort_order")
ON CONFLICT DO NOTHING;
