import { NextResponse } from 'next/server';

/**
 * /sw.js — the service worker.
 *
 * ── The one decision that matters: nothing authenticated is ever cached ──
 * A service worker that cached pages would be the fastest thing in this
 * product and the most dangerous. Every portal page is per-person and
 * per-tenant: a cached `/parent/fees` is one family's bill, sitting in a
 * cache that outlives the session, on a handset that in this market is
 * frequently shared. Signing out does not clear it, and the next person to
 * open the app on a dead connection would be served it.
 *
 * So navigations are **network-only**, with one fallback: if the network fails
 * outright, serve `/offline`, a static page that knows nothing about anybody.
 * That is the whole caching policy for HTML, and it is not a limitation to be
 * removed later — anything else needs a cache keyed on the session and purged
 * on sign-out, which is a Sprint 15 conversation alongside Web Push.
 *
 * What *is* cached is the app shell: build-hashed `/_next/static/*` assets and
 * the offline page. Those are identical for every viewer and are already
 * immutable by URL, so a stale one is impossible rather than merely unlikely.
 *
 * ── Why this is a route and not `public/sw.js` ───────────────────────────
 * There is no `public/` directory in this repository (`STATE.md` §5), and the
 * standalone artifact does not copy one that does not exist. A route handler
 * ships with the build, needs no deploy step, and lets the header below be set
 * — which a static file could not do.
 *
 * `Service-Worker-Allowed: /` is what permits a worker served from this path to
 * claim the whole origin as its scope.
 */

export const runtime = 'nodejs';
export const dynamic = 'force-static';

/**
 * Bumping this discards every cache the previous worker made.
 *
 * It is deliberately a constant rather than a build hash: the only thing cached
 * is content-hashed already, so a version bump is for changing *policy*, and it
 * should be a decision somebody makes rather than something that happens on
 * every deploy.
 */
const CACHE_VERSION = 'v1';

const SERVICE_WORKER = `
// Generated by app/sw.js/route.ts — see that file for why this caches so little.
const CACHE = 'sms-shell-${CACHE_VERSION}';
const OFFLINE_URL = '/offline';

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll([OFFLINE_URL]))
      // A failed pre-cache must not stop the worker installing. The app works
      // without it; only the offline fallback is lost.
      .catch(() => undefined)
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;

  // Only GET. A POST replayed from a cache would take a payment twice.
  if (request.method !== 'GET') return;

  const url = new URL(request.url);

  // Same origin only. Another origin's response is not ours to store.
  if (url.origin !== self.location.origin) return;

  // Never touch the API. Every one of these is per-person data.
  if (url.pathname.startsWith('/api/')) return;

  // Build-hashed static assets: cache-first, because the URL changes whenever
  // the content does, so a stale hit is not possible.
  if (url.pathname.startsWith('/_next/static/')) {
    event.respondWith(
      caches.match(request).then((hit) => {
        if (hit) return hit;
        return fetch(request).then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        });
      }),
    );
    return;
  }

  // Everything else that is a page: network-only, offline page on failure.
  // Nothing authenticated is ever written to a cache. See the route docblock.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() =>
        caches.match(OFFLINE_URL).then((hit) => hit ?? Response.error()),
      ),
    );
  }
});
`.trimStart();

export function GET(): NextResponse {
  return new NextResponse(SERVICE_WORKER, {
    headers: {
      'Content-Type': 'text/javascript; charset=utf-8',
      // Without this a worker served from /sw.js may only control /sw.js.
      'Service-Worker-Allowed': '/',
      // The worker itself must never be cached hard: it is the only thing that
      // can replace a bad worker, and a browser holding a stale copy for a year
      // is an application that cannot be fixed.
      'Cache-Control': 'public, max-age=0, must-revalidate',
    },
  });
}
