import 'server-only';

import { and, eq, inArray, isNull, lt, ne, or } from 'drizzle-orm';

import {
  familyChallans,
  feeChallans,
  feeStructures,
  feeTypes,
  grades,
  lateFeeRules,
  schoolUsers,
  sections,
  studentEnrollments,
  studentGuardians,
  studentProfiles,
} from '@/db/schema';

import { getActiveAcademicYear } from './admissions-queries';
import { describeError } from './describe-error';
import { db } from './drizzle';
import { generateChallan, ChallanGenerationError } from './fee-challans';
import { generateFamilyChallan, FamilyChallanError } from './family-challans';
import { toDateOnly } from './fee-queries';
import { normalizeCnic } from './national-id';

/**
 * Raising next month's vouchers on a timer (Sprint 27, item A5).
 *
 * ── The model this exists to serve ───────────────────────────────────────
 * A school here is **pre-paid**. October's fee is billed *during September* and
 * falls due on the 10th of October. So the run fires on a day of month `M − 1`
 * — the 25th unless the school says otherwise — and bills month `M`, with the
 * year rolling over: a run on 28 December 2026 bills January 2027.
 *
 * That asymmetry is the whole reason this is a separate sweeper from
 * `lib/voucher-auto-send.ts` rather than a flag on it. The send emails *this*
 * month's vouchers; this one raises *next* month's.
 *
 * ── Off at every school, and it stays off ────────────────────────────────
 * `auto_generate_vouchers` defaults to false and nothing here turns it on.
 * A scheduler that began billing at a school which never asked for it would be
 * the worst thing this module could do, and a voucher a parent has already
 * been shown cannot be recalled any more than an email can.
 *
 * ── Claimed, not checked ─────────────────────────────────────────────────
 * `instrumentation.ts` starts one of these per server process and production
 * runs **seven**. A read followed by an `if` lets all seven pass the same test
 * and bill the same school seven times over — and unlike a duplicated email,
 * seven vouchers are seven documents in a register with seven numbers.
 *
 * So a school is claimed with a conditional `UPDATE … RETURNING`:
 * `auto_generate_last_run_on` moves to today only where it is null or earlier,
 * and Postgres decides that on one row under one lock. CLAUDE.md's rule, and
 * the same shape `voucher-auto-send.ts` uses beside it.
 *
 * **Claim first, hand it back on a throw.** `releaseClaim` sets the column to
 * null for the same reason the send sweeper does: a failure recorded as a run
 * is a month the school believes it billed and did not.
 *
 * ── Belt and braces, in the database ─────────────────────────────────────
 * Even with all of that, the run also *skips* anyone already holding a live
 * voucher for the target month, and `fee_challans_student_month_year_idx`
 * refuses a second one regardless. Three defences, because the failure mode is
 * a parent billed twice and the recovery is a conversation at a counter.
 */

/** The 25th — late enough that the month's changes are in, early enough to post. */
export const DEFAULT_AUTO_GENERATE_DAY = 25;

/** How often the sweep looks. A minute is well inside "the right day". */
const SWEEP_SECONDS = 60;

let sweepTimer: NodeJS.Timeout | null = null;
let sweeping = false;

/** One school the sweep has taken ownership of for today. */
interface Claim {
  locationId: string;
  familyVouchers: boolean;
}

/** What one school's run did, for the log line and for the tests. */
export interface GenerationTally {
  raised: number;
  families: number;
  alreadyBilled: number;
  skipped: number;
}

/**
 * The month a run on this date bills, with the year rolling over.
 *
 * Exported and pure so `check-sprint27` can assert the December case without a
 * database: a run on 28 December 2026 bills January **2027**, and getting that
 * wrong bills a month twelve months in the past.
 */
export function targetPeriod(runDate: Date): { billingMonth: number; billingYear: number } {
  const month = runDate.getMonth() + 1;
  return month === 12
    ? { billingMonth: 1, billingYear: runDate.getFullYear() + 1 }
    : { billingMonth: month + 1, billingYear: runDate.getFullYear() };
}

/**
 * Takes today's run for every school due one, and returns what it took.
 *
 * The `WHERE` is the whole design: the school has the feature on, today is its
 * chosen day, and it has not already run today. Any process losing the race
 * simply gets fewer rows back.
 */
async function claimSchools(today: string, dayOfMonth: number): Promise<Claim[]> {
  return db
    .update(lateFeeRules)
    .set({ autoGenerateLastRunOn: today })
    .where(
      and(
        eq(lateFeeRules.autoGenerateVouchers, true),
        eq(lateFeeRules.autoGenerateDay, dayOfMonth),
        or(
          isNull(lateFeeRules.autoGenerateLastRunOn),
          // `lt`, not a raw `sql` template. A comparison against a column goes
          // through the operator so the value is mapped for the driver — see
          // CLAUDE.md, and the scheduled announcements that never released.
          lt(lateFeeRules.autoGenerateLastRunOn, today),
        ),
      ),
    )
    .returning({
      locationId: lateFeeRules.locationId,
      familyVouchers: lateFeeRules.autoGenerateFamilyVouchers,
    });
}

/**
 * Hands a claim back, so a transient failure is not recorded as a run.
 *
 * Set to **null**, not to the value it held before, for the reason
 * `voucher-auto-send.ts` gives at length: `RETURNING` yields the new row, so
 * recovering the old one would need the read this design exists to avoid. Null
 * is the honest and sufficient value — the column means one thing to the claim,
 * "not today", and null passes that test.
 */
async function releaseClaim(claim: Claim): Promise<void> {
  await db
    .update(lateFeeRules)
    .set({ autoGenerateLastRunOn: null })
    .where(eq(lateFeeRules.locationId, claim.locationId));
}

/** One actively-enrolled student the run would bill. */
interface Candidate {
  studentProfileId: string;
  studentName: string;
  /** The primary guardian's family key, or null when there is nothing to group on. */
  familyKey: string | null;
  /** The guardian row a family voucher would be addressed to. */
  guardianId: string | null;
}

/**
 * Everyone actively enrolled in a grade that actually has a price list.
 *
 * ── Why the fee structure is a join and not a later refusal ──────────────
 * `generateChallan` throws `no_fee_structure` for a grade with no prices, and
 * a run over a school with two unpriced grades would otherwise log two hundred
 * identical failures. Those grades are not a failure — they are grades the
 * school has not priced yet, which is a normal state in September — so they
 * are excluded here and counted as skipped.
 *
 * The family key is the **primary contact's** CNIC where there is a whole one
 * and their phone number otherwise: the same two keys `lib/siblings.ts` and
 * `groupOpenChallans` match on, in the same precedence. It is deliberately not
 * the full union-find those two run: this sweeper groups children who share a
 * primary contact, and a family split across two differently-recorded guardian
 * rows is billed as two families rather than mis-grouped. The screens that do
 * run the union-find are where a clerk fixes that, and doing it wrong on a
 * timer at three in the morning is the outcome to avoid.
 */
async function candidatesFor(
  locationId: string,
  academicYearId: string,
): Promise<Candidate[]> {
  const rows = await db
    .selectDistinctOn([studentProfiles.id], {
      studentProfileId: studentProfiles.id,
      studentName: schoolUsers.name,
      guardianId: studentGuardians.id,
      cnic: studentGuardians.cnic,
      phone: studentGuardians.phone,
    })
    .from(studentEnrollments)
    .innerJoin(studentProfiles, eq(studentProfiles.id, studentEnrollments.studentProfileId))
    .innerJoin(schoolUsers, eq(schoolUsers.id, studentProfiles.schoolUserId))
    .innerJoin(sections, eq(sections.id, studentEnrollments.sectionId))
    .innerJoin(grades, eq(grades.id, sections.gradeId))
    .innerJoin(
      feeStructures,
      and(
        eq(feeStructures.gradeId, grades.id),
        eq(feeStructures.academicYearId, academicYearId),
        eq(feeStructures.locationId, locationId),
      ),
    )
    .innerJoin(
      // Through `fee_types`, because a grade priced entirely against heads the
      // school has since retired has no billable line — `listBillableStructures`
      // filters on exactly this, and a candidate list that disagreed with the
      // pricer would log `no_monthly_fees` once per child.
      feeTypes,
      and(eq(feeTypes.id, feeStructures.feeTypeId), eq(feeTypes.isActive, true)),
    )
    .leftJoin(
      studentGuardians,
      and(
        eq(studentGuardians.studentProfileId, studentProfiles.id),
        eq(studentGuardians.isPrimaryContact, true),
      ),
    )
    .where(
      and(
        eq(studentEnrollments.locationId, locationId),
        eq(studentEnrollments.academicYearId, academicYearId),
        eq(studentEnrollments.status, 'active'),
      ),
    );

  return rows.map((row) => {
    const cnic = normalizeCnic(row.cnic);
    const phone = row.phone ?? '';

    return {
      studentProfileId: row.studentProfileId,
      studentName: row.studentName,
      guardianId: row.guardianId,
      familyKey:
        cnic !== null ? `cnic:${cnic}` : phone === '' ? null : `phone:${phone}`,
    };
  });
}

/** Students already holding a live voucher for the target month. */
async function alreadyBilledIds(
  locationId: string,
  academicYearId: string,
  billingMonth: number,
  billingYear: number,
  studentProfileIds: readonly string[],
): Promise<Set<string>> {
  if (studentProfileIds.length === 0) return new Set();

  const rows = await db
    .select({ studentProfileId: feeChallans.studentProfileId })
    .from(feeChallans)
    .where(
      and(
        eq(feeChallans.locationId, locationId),
        eq(feeChallans.academicYearId, academicYearId),
        eq(feeChallans.billingMonth, billingMonth),
        eq(feeChallans.billingYear, billingYear),
        // The predicate the partial unique index carries. A cancelled voucher
        // does not occupy the month, so a school that cancelled a month in
        // order to re-bill it gets that month raised rather than skipped.
        ne(feeChallans.status, 'cancelled'),
        inArray(feeChallans.studentProfileId, [...studentProfileIds]),
      ),
    );

  return new Set(rows.map((row) => row.studentProfileId));
}

/** Families already holding a live wrapper for the target month. */
async function alreadyWrappedGuardians(
  locationId: string,
  academicYearId: string,
  billingMonth: number,
  billingYear: number,
): Promise<Set<string>> {
  const rows = await db
    .select({ guardianId: familyChallans.guardianId })
    .from(familyChallans)
    .where(
      and(
        eq(familyChallans.locationId, locationId),
        eq(familyChallans.academicYearId, academicYearId),
        eq(familyChallans.billingMonth, billingMonth),
        eq(familyChallans.billingYear, billingYear),
        ne(familyChallans.status, 'cancelled'),
      ),
    );

  return new Set(rows.map((row) => row.guardianId));
}

/**
 * Bills one school for one month.
 *
 * Exported so `check-sprint27` and a future support script can drive a single
 * school without going through the timer. It does **not** claim — the caller
 * owns that decision — so calling it directly bills whether or not the school
 * has already been billed today, which is right for a deliberate re-run and
 * wrong for a timer.
 */
export async function generateMonthForSchool(params: {
  locationId: string;
  academicYearId: string;
  billingMonth: number;
  billingYear: number;
  actorUid: string;
  familyVouchers: boolean;
}): Promise<GenerationTally> {
  const tally: GenerationTally = { raised: 0, families: 0, alreadyBilled: 0, skipped: 0 };

  const candidates = await candidatesFor(params.locationId, params.academicYearId);
  if (candidates.length === 0) return tally;

  const billed = await alreadyBilledIds(
    params.locationId,
    params.academicYearId,
    params.billingMonth,
    params.billingYear,
    candidates.map((candidate) => candidate.studentProfileId),
  );

  const pending = candidates.filter(
    (candidate) => !billed.has(candidate.studentProfileId),
  );
  tally.alreadyBilled = candidates.length - pending.length;

  const families = new Map<string, Candidate[]>();
  const singles: Candidate[] = [];

  if (params.familyVouchers) {
    for (const candidate of pending) {
      if (candidate.familyKey === null) {
        singles.push(candidate);
        continue;
      }
      families.set(candidate.familyKey, [
        ...(families.get(candidate.familyKey) ?? []),
        candidate,
      ]);
    }
  } else {
    singles.push(...pending);
  }

  const wrapped = params.familyVouchers
    ? await alreadyWrappedGuardians(
        params.locationId,
        params.academicYearId,
        params.billingMonth,
        params.billingYear,
      )
    : new Set<string>();

  for (const [, group] of families) {
    // One child is not a family. They are billed individually, which is the
    // same voucher they would have received before this feature existed.
    if (group.length < 2) {
      singles.push(...group);
      continue;
    }

    const guardianId = group[0]?.guardianId ?? null;
    if (guardianId === null) {
      singles.push(...group);
      continue;
    }

    // The family already has this month's wrapper. Not a failure and not
    // something to retry — the run is being repeated, which is exactly what it
    // is built to survive.
    if (wrapped.has(guardianId)) {
      tally.alreadyBilled += group.length;
      continue;
    }

    try {
      const voucher = await generateFamilyChallan({
        locationId: params.locationId,
        actorUid: params.actorUid,
        guardianId,
        academicYearId: params.academicYearId,
        billingMonth: params.billingMonth,
        billingYear: params.billingYear,
      });

      tally.families += 1;
      tally.raised += voucher.members;
    } catch (error) {
      /*
       * A family that cannot be clubbed is billed child by child instead.
       *
       * The common reason is one sibling already holding this month's voucher
       * — which `generateFamilyChallan` refuses rather than cancelling, and
       * rightly: a timer must never tear up a document a parent may be
       * holding. The rest of the family still needs billing, so they fall
       * through to the individual path below.
       */
      if (error instanceof FamilyChallanError) {
        console.warn(
          `[auto-generate] ${params.locationId}: family voucher for ${guardianId} not raised — ${error.message}`,
        );
        singles.push(...group);
        continue;
      }

      throw error;
    }
  }

  for (const candidate of singles) {
    try {
      await generateChallan(db, {
        locationId: params.locationId,
        studentProfileId: candidate.studentProfileId,
        academicYearId: params.academicYearId,
        billingMonth: params.billingMonth,
        billingYear: params.billingYear,
        actorUid: params.actorUid,
      });

      tally.raised += 1;
    } catch (error) {
      // One student's data must not abandon the other three hundred. The
      // reasons are the same ones the bulk generator reports on screen — no
      // enrollment, no priced fee heads, a voucher raised a second ago by
      // somebody at a counter — and none of them is a reason to stop.
      if (error instanceof ChallanGenerationError) {
        tally.skipped += 1;
        console.warn(
          `[auto-generate] ${params.locationId}: ${candidate.studentName} skipped — ${error.message}`,
        );
        continue;
      }

      throw error;
    }
  }

  return tally;
}

/**
 * One tick. Returns how many schools were billed.
 *
 * Each school is claimed, worked and — on a throw — released, inside its own
 * try/catch: one school's failure must not abandon the rest, and a throw here
 * would reach a timer callback with nothing to catch it.
 */
export async function sweepAutoGenerateVouchers(now: Date = new Date()): Promise<number> {
  const today = toDateOnly(now);
  const claims = await claimSchools(today, now.getDate());
  const { billingMonth, billingYear } = targetPeriod(now);

  let billed = 0;

  for (const claim of claims) {
    try {
      const year = await getActiveAcademicYear(claim.locationId);

      /*
       * No active academic year is not an error, and not a claim to hand back.
       *
       * A school between years has nothing to bill against, and re-trying
       * every minute until midnight fixes nothing — the year is set by a
       * person on a screen, not by waiting. The claim stands: the day's run
       * happened and found no year.
       */
      if (year === null) {
        console.info(
          `[auto-generate] ${claim.locationId}: no active academic year, nothing raised`,
        );
        continue;
      }

      const tally = await generateMonthForSchool({
        locationId: claim.locationId,
        academicYearId: year.id,
        billingMonth,
        billingYear,
        // The run has no person behind it, and saying so is better than
        // attributing four hundred vouchers to whoever last signed in.
        actorUid: 'system:auto-generate',
        familyVouchers: claim.familyVouchers,
      });

      if (tally.raised > 0) billed += 1;

      console.info(
        `[auto-generate] ${claim.locationId}: ${String(tally.raised)} raised, ${String(tally.families)} families, ${String(tally.alreadyBilled)} already billed, ${String(tally.skipped)} skipped`,
      );
    } catch (caught) {
      // Handed back, so tomorrow's tick — or the next process's — tries again.
      await releaseClaim(claim).catch((error: unknown) => {
        console.error(
          `[auto-generate] could not release the claim for ${claim.locationId}: ${describeError(error)}`,
        );
      });

      console.error(
        `[auto-generate] ${claim.locationId} failed: ${describeError(caught)}`,
      );
    }
  }

  return billed;
}

/** Starts the sweep. Idempotent, like the send sweeper beside it. */
export function startVoucherAutoGenerate(): void {
  if (sweepTimer !== null) return;

  sweepTimer = setInterval(() => {
    if (sweeping) return;
    sweeping = true;

    void sweepAutoGenerateVouchers()
      .then((billed) => {
        if (billed > 0) console.info(`[auto-generate] billed ${String(billed)} school(s)`);
      })
      .catch((caught: unknown) => {
        console.error(`[auto-generate] sweep failed: ${describeError(caught)}`);
      })
      .finally(() => {
        sweeping = false;
      });
  }, SWEEP_SECONDS * 1000);

  // Never a reason to refuse to shut down.
  sweepTimer.unref?.();

  console.info(
    `[auto-generate] voucher generation scheduler started (every ${String(SWEEP_SECONDS)}s)`,
  );
}
